#include "AlarmMng.h"
#include "language/languagePublic.h"
struct AlmlevelStruct   almLevelString;
struct AlmDevTypeStruct almDevTypeString;
struct AlmDevLogStruct  almDevLogString[eAlmDevNum];

void AlarmMngInit()
{
    //
    almLevelString.AlmLevel[0] = langN.show[langEnum::strNorEve]; //"普通事件";
    almLevelString.AlmLevel[1] = langN.show[langEnum::strGenAlm]; //"一般告警";
    almLevelString.AlmLevel[2] = langN.show[langEnum::strUrgAlm]; //"严重告警";

    //
    almDevTypeString.AlmDevType[0] =  langN.show[langEnum::strCabinet]; //"机柜";
    almDevTypeString.AlmDevType[1] =  "UPS";
    almDevTypeString.AlmDevType[2] =  langN.show[langEnum::strAc]; //"空调";
    almDevTypeString.AlmDevType[3] =  langN.show[langEnum::strHumiture]; //"温湿度";
    almDevTypeString.AlmDevType[4] =  "PDU";
    almDevTypeString.AlmDevType[5] =  langN.show[langEnum::strWaterLeak]; //"水浸";
    almDevTypeString.AlmDevType[6] =  langN.show[langEnum::strSmsDev]; //"短信";
    almDevTypeString.AlmDevType[7] =  langN.show[langEnum::strITPdc]; //"IT配电柜";
    almDevTypeString.AlmDevType[8] =  langN.show[langEnum::strVMeter]; //"电量仪";
    almDevTypeString.AlmDevType[9] =  langN.show[langEnum::strSpds]; //"列头柜";
    almDevTypeString.AlmDevType[10] = langN.show[langEnum::strExtDc]; //"控制模块";
    almDevTypeString.AlmDevType[11] = langN.show[langEnum::strBms]; //"电池巡检仪";
    almDevTypeString.AlmDevType[12] = "ATS";
    almDevTypeString.AlmDevType[13] = langN.show[langEnum::strMAUDev]; //"新风机";
    almDevTypeString.AlmDevType[14] = langN.show[langEnum::strDisplayMode]; //"显示模块";
    almDevTypeString.AlmDevType[15] = langN.show[langEnum::strFanCtrlr]; //"风扇控制器";
    almDevTypeString.AlmDevType[16] = langN.show[langEnum::strCtrlBox]; //"配电控制单元";

    //UPS logID消息
    almDevLogString[eAlmDevUps].AlmDevLogID[0] =  {langN.show[langEnum::strCommFail],true };
    almDevLogString[eAlmDevUps].AlmDevLogID[1] =  {langN.show[langEnum::strCommFail],false};
    almDevLogString[eAlmDevUps].AlmDevLogID[2] =  {langN.show[langEnum::strNoSupp],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[3] =  {langN.show[langEnum::strUpsSupp],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[4] =  {langN.show[langEnum::strBypSupp],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[5] =  {langN.show[langEnum::strMaintCbClose],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[6] =  {langN.show[langEnum::strMaintCbOpen],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[7] =  {langN.show[langEnum::strBattFloat],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[8] =  {langN.show[langEnum::strBattBoost],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[9] =  {langN.show[langEnum::strBattDisChar],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[10] = {langN.show[langEnum::strHaveBatt],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[11] = {langN.show[langEnum::strNoBatt],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[12] = {langN.show[langEnum::strBatTestSucc],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[13] = {langN.show[langEnum::strBatTestFail],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[14] = {langN.show[langEnum::strBatMntnSucc],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[15] = {langN.show[langEnum::strBatMntnFail],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[16] = {langN.show[langEnum::strEPO],true };
    almDevLogString[eAlmDevUps].AlmDevLogID[17] = {langN.show[langEnum::strEPO],false};
    almDevLogString[eAlmDevUps].AlmDevLogID[18] = {langN.show[langEnum::strFanFail],true };
    almDevLogString[eAlmDevUps].AlmDevLogID[19] = {langN.show[langEnum::strFanFail],false};
    almDevLogString[eAlmDevUps].AlmDevLogID[20] = {langN.show[langEnum::strTmpAbnor],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[21] = {langN.show[langEnum::strTmpAbnor],false};
    almDevLogString[eAlmDevUps].AlmDevLogID[22] = {langN.show[langEnum::strUpsStsRecFail],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[23] = {langN.show[langEnum::strUpsStsRecFail],false};
    almDevLogString[eAlmDevUps].AlmDevLogID[24] = {langN.show[langEnum::strUtilityAbnor],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[25] = {langN.show[langEnum::strUtilityAbnor],false};
    almDevLogString[eAlmDevUps].AlmDevLogID[26] = {langN.show[langEnum::strBypFail],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[27] = {langN.show[langEnum::strBypFail],false};
    almDevLogString[eAlmDevUps].AlmDevLogID[28] = {langN.show[langEnum::strBypVoltAbonor],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[29] = {langN.show[langEnum::strBypVoltAbonor],false};
    almDevLogString[eAlmDevUps].AlmDevLogID[30] = {langN.show[langEnum::strBypFreqUntrack],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[31] = {langN.show[langEnum::strBypFreqUntrack],false};
    almDevLogString[eAlmDevUps].AlmDevLogID[32] = {langN.show[langEnum::strBypOvLoad],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[33] = {langN.show[langEnum::strBypOvLoad],false};
    almDevLogString[eAlmDevUps].AlmDevLogID[34] = {langN.show[langEnum::strBypOvLoadTO],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[35] = {langN.show[langEnum::strBypOvLoadTO],false};
    almDevLogString[eAlmDevUps].AlmDevLogID[36] = {langN.show[langEnum::strBypSeqInverConn],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[37] = {langN.show[langEnum::strBypSeqInverConn],false};
    almDevLogString[eAlmDevUps].AlmDevLogID[38] = {langN.show[langEnum::strInvFail],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[39] = {langN.show[langEnum::strInvFail],false};
    almDevLogString[eAlmDevUps].AlmDevLogID[40] = {langN.show[langEnum::strOpOverLoad],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[41] = {langN.show[langEnum::strOpOverLoad],false};
    almDevLogString[eAlmDevUps].AlmDevLogID[42] = {langN.show[langEnum::strInvOvLoadTO],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[43] = {langN.show[langEnum::strInvOvLoadTO],false};
    almDevLogString[eAlmDevUps].AlmDevLogID[44] = {langN.show[langEnum::strOpShrt],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[45] = {langN.show[langEnum::strOpShrt],false};
    almDevLogString[eAlmDevUps].AlmDevLogID[46] = {langN.show[langEnum::strBatt]+" "+langN.show[langEnum::strVoltLwrLwLimit],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[47] = {langN.show[langEnum::strBatt]+" "+langN.show[langEnum::strVoltLwrLwLimit],false};
    almDevLogString[eAlmDevUps].AlmDevLogID[48] = {langN.show[langEnum::strBattEOD],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[49] = {langN.show[langEnum::strBattEOD],false};
    almDevLogString[eAlmDevUps].AlmDevLogID[50] = {langN.show[langEnum::strBattRever],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[51] = {langN.show[langEnum::strBattRever],false};
    almDevLogString[eAlmDevUps].AlmDevLogID[52] = {langN.show[langEnum::strInvBanSuppPwr],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[53] = {langN.show[langEnum::strInvBanSuppPwr],false};
    almDevLogString[eAlmDevUps].AlmDevLogID[54] = {langN.show[langEnum::strFaultClr],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[55] = {langN.show[langEnum::strManuXfeToByp],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[56] = {langN.show[langEnum::strEscManuXfeToByp],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[57] = {langN.show[langEnum::strBattTest],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[58] = {langN.show[langEnum::strBattMntn],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[59] = {langN.show[langEnum::strManuBoost],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[60] = {langN.show[langEnum::strManuFloat],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[61] = {langN.show[langEnum::strStopTest],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[62] = {langN.show[langEnum::strManuAdd],true};
    almDevLogString[eAlmDevUps].AlmDevLogID[63] = {langN.show[langEnum::strManuDel],true};


    //机柜 logID消息
    almDevLogString[eAlmDevCap].AlmDevLogID[0] =  {langN.show[langEnum::strRechFanOpAlm],true};
    almDevLogString[eAlmDevCap].AlmDevLogID[1] =  {langN.show[langEnum::strRechFanOpAlm],false};
    almDevLogString[eAlmDevCap].AlmDevLogID[2] =  {langN.show[langEnum::strClodChanTmpHigh],true};
    almDevLogString[eAlmDevCap].AlmDevLogID[3] =  {langN.show[langEnum::strClodChanTmpHigh],false};
    almDevLogString[eAlmDevCap].AlmDevLogID[4] =  {langN.show[langEnum::strClodChanTmpLow],true};
    almDevLogString[eAlmDevCap].AlmDevLogID[5] =  {langN.show[langEnum::strClodChanTmpLow],false};
    almDevLogString[eAlmDevCap].AlmDevLogID[6] =  {langN.show[langEnum::strClodChanHumHigh],true};
    almDevLogString[eAlmDevCap].AlmDevLogID[7] =  {langN.show[langEnum::strClodChanHumHigh],false};
    almDevLogString[eAlmDevCap].AlmDevLogID[8] =  {langN.show[langEnum::strClodChanHumLow],true};
    almDevLogString[eAlmDevCap].AlmDevLogID[9] =  {langN.show[langEnum::strClodChanHumLow],false};
    almDevLogString[eAlmDevCap].AlmDevLogID[10] = {langN.show[langEnum::strHotChanTmpHigh],true};
    almDevLogString[eAlmDevCap].AlmDevLogID[11] = {langN.show[langEnum::strHotChanTmpHigh],false};
    almDevLogString[eAlmDevCap].AlmDevLogID[12] = {langN.show[langEnum::strHotChanTmpLow],true};
    almDevLogString[eAlmDevCap].AlmDevLogID[13] = {langN.show[langEnum::strHotChanTmpLow],false};
    almDevLogString[eAlmDevCap].AlmDevLogID[14] = {langN.show[langEnum::strHotChanHumHigh],true};
    almDevLogString[eAlmDevCap].AlmDevLogID[15] = {langN.show[langEnum::strHotChanHumHigh],false};
    almDevLogString[eAlmDevCap].AlmDevLogID[16] = {langN.show[langEnum::strHotChanHumLow],true};
    almDevLogString[eAlmDevCap].AlmDevLogID[17] = {langN.show[langEnum::strHotChanHumLow],false};
    almDevLogString[eAlmDevCap].AlmDevLogID[18] = {langN.show[langEnum::strClearHisLog],true};
    almDevLogString[eAlmDevCap].AlmDevLogID[19] = {langN.show[langEnum::strClearHisData],true};
    almDevLogString[eAlmDevCap].AlmDevLogID[20] = {langN.show[langEnum::strSysTimeSync],true};
    almDevLogString[eAlmDevCap].AlmDevLogID[21] = {langN.show[langEnum::strSysSwUpdate],true};
    almDevLogString[eAlmDevCap].AlmDevLogID[22] = {langN.show[langEnum::strEmSendFail],true};
    almDevLogString[eAlmDevCap].AlmDevLogID[23] = {langN.show[langEnum::strSDCRemove], true};
    almDevLogString[eAlmDevCap].AlmDevLogID[24] = {langN.show[langEnum::strSDCRemove],false};
    almDevLogString[eAlmDevCap].AlmDevLogID[25] = {langN.show[langEnum::strSDInsfSpace], true};
    almDevLogString[eAlmDevCap].AlmDevLogID[26] = {langN.show[langEnum::strSDInsfSpace],false};
    almDevLogString[eAlmDevCap].AlmDevLogID[27] = {langN.show[langEnum::strMemInsfSpace], true};
    almDevLogString[eAlmDevCap].AlmDevLogID[28] = {langN.show[langEnum::strMemInsfSpace],false};
    almDevLogString[eAlmDevCap].AlmDevLogID[29] = {langN.show[langEnum::strDataSaveFail], true};
    almDevLogString[eAlmDevCap].AlmDevLogID[30] = {langN.show[langEnum::strDataSaveFail],false};
    almDevLogString[eAlmDevCap].AlmDevLogID[31] = {langN.show[langEnum::strDataToSD], true};
    almDevLogString[eAlmDevCap].AlmDevLogID[32] = {langN.show[langEnum::strDataToMem], true};
    almDevLogString[eAlmDevCap].AlmDevLogID[33] = {langN.show[langEnum::strFireAlm], true};
    almDevLogString[eAlmDevCap].AlmDevLogID[34] = {langN.show[langEnum::strFireAlm],false};
    almDevLogString[eAlmDevCap].AlmDevLogID[35] = {langN.show[langEnum::strDoorProjectile], true};
    almDevLogString[eAlmDevCap].AlmDevLogID[36] = {langN.show[langEnum::strUtilityAbnor], true};
    almDevLogString[eAlmDevCap].AlmDevLogID[37] = {langN.show[langEnum::strUtilityAbnor],false};


    //空调 logID消息
    almDevLogString[eAlmDevAc].AlmDevLogID[0] = {langN.show[strCommFail],true};//通讯失败
    almDevLogString[eAlmDevAc].AlmDevLogID[1] = {langN.show[strCommFail],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[2] = {langN.show[strManuAdd],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[3] = {langN.show[strManuDel]	,true};
    almDevLogString[eAlmDevAc].AlmDevLogID[4] = {langN.show[strAcStsIntegratedAlm],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[5] = {langN.show[strAcStsIntegratedAlm],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[6] = {langN.show[strSD],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[7] = {langN.show[strSU],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[8] = {langN.show[strRF_IT_OH_x10_1],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[9] = {langN.show[strRF_IT_OH_x10_1],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[10] = {langN.show[strRF_IT_OH_x10_1],true};  //空调回风低温告警
    almDevLogString[eAlmDevAc].AlmDevLogID[11] = {langN.show[strRF_IT_OH_x10_1],false}; //空调回风低温告警
    almDevLogString[eAlmDevAc].AlmDevLogID[12] = {langN.show[strRF_IT_OHH_x10],true};   //"空调回风高湿告警"
    almDevLogString[eAlmDevAc].AlmDevLogID[13] = {langN.show[strRF_IT_OHH_x10],false};  //"空调回风高湿告警"
    almDevLogString[eAlmDevAc].AlmDevLogID[14] = {langN.show[strRF_IT_OHL_x10],true};   //"空调回风低湿告警"
    almDevLogString[eAlmDevAc].AlmDevLogID[15] = {langN.show[strRF_IT_OHL_x10],false};  //"空调回风低湿告警"
    almDevLogString[eAlmDevAc].AlmDevLogID[16] = {langN.show[strRF_OT_OH_x10_1],true};  //空调送风高温告警
    almDevLogString[eAlmDevAc].AlmDevLogID[17] = {langN.show[strRF_OT_OH_x10_1],false}; //空调送风高温告警
    almDevLogString[eAlmDevAc].AlmDevLogID[18] = {langN.show[strRF_OT_OL_x10_1],true};  //空调送风低温告警
    almDevLogString[eAlmDevAc].AlmDevLogID[19] = {langN.show[strRF_OT_OL_x10_1],false}; //空调送风低温告警
    almDevLogString[eAlmDevAc].AlmDevLogID[20] = {langN.show[strIS_SMK_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[21] = {langN.show[strIS_SMK_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[22] = {langN.show[strIS_FSD_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[23] = {langN.show[strIS_FSD_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[24] = {langN.show[strIS_SYSDW_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[25] = {langN.show[strIS_SYSDW_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[26] = {langN.show[strIS_LL_SV_STS]+langN.show[strOpen],true};    //"空调液管电磁阀   开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[27] = {langN.show[strIS_LL_SV_STS]+langN.show[strOpen],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[28] = {langN.show[strIS_CPUMP_STS]+langN.show[strOpen],true};//"空调冷凝排水泵开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[29] = {langN.show[strIS_CPUMP_STS]+langN.show[strOpen],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[30] = {langN.show[strIS_IPW_A_VOH_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[31] = {langN.show[strIS_IPW_A_VOH_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[32] = {langN.show[strIS_IPW_B_VOH_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[33] = {langN.show[strIS_IPW_B_VOH_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[34] = {langN.show[strIS_IPW_C_VOH_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[35] = {langN.show[strIS_IPW_C_VOH_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[36] = {langN.show[strIS_IPW_A_VOL_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[37] = {langN.show[strIS_IPW_A_VOL_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[38] = {langN.show[strIS_IPW_B_VOL_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[39] = {langN.show[strIS_IPW_B_VOL_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[40] = {langN.show[strIS_IPW_C_VOL_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[41] = {langN.show[strIS_IPW_C_VOL_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[42] = {langN.show[strIS_IPW_PHUB_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[43] = {langN.show[strIS_IPW_PHUB_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[44] = {langN.show[strIS_IPW_FOL_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[45] = {langN.show[strIS_IPW_FOL_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[46] = {langN.show[strIS_IPW_FOH_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[47] = {langN.show[strIS_IPW_FOH_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[48] = {langN.show[strIS_IPW_A_PHL_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[49] = {langN.show[strIS_IPW_A_PHL_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[50] = {langN.show[strIS_IPW_B_PHL_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[51] = {langN.show[strIS_IPW_B_PHL_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[52] = {langN.show[strIS_IPW_C_PHL_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[53] = {langN.show[strIS_IPW_C_PHL_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[54] = {langN.show[strIS_IPW_PHSE_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[55] = {langN.show[strIS_IPW_PHSE_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[56] = {langN.show[strIR_EFAN]+langN.show[strOpen],true};   //"空调内风机开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[57] = {langN.show[strIR_EFAN]+langN.show[strOpen],false};  //"空调内风机开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[58] = {langN.show[strIS_EFAN1_ALM],true};//空调内风机1故障告警
    almDevLogString[eAlmDevAc].AlmDevLogID[59] = {langN.show[strIS_EFAN1_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[60] = {langN.show[strIS_EFAN2_ALM],true};//空调内风机2故障告警
    almDevLogString[eAlmDevAc].AlmDevLogID[61] = {langN.show[strIS_EFAN2_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[62] = {langN.show[strIS_EFAN3_ALM],true};//空调内风机3故障告警
    almDevLogString[eAlmDevAc].AlmDevLogID[63] = {langN.show[strIS_EFAN3_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[64] = {langN.show[strRF_AF_LOST_ALM_EN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[65] = {langN.show[strRF_AF_LOST_ALM_EN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[66] = {langN.show[strFilterClog],true};  //"空调过滤网堵塞告警"
    almDevLogString[eAlmDevAc].AlmDevLogID[67] = {langN.show[strFilterClog],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[68] = {langN.show[strIS_DI_CFAN_ALM]+langN.show[strOpen],true}; //"空调外风机开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[69] = {langN.show[strIS_DI_CFAN_ALM]+langN.show[strOpen],false};  //"空调外风机开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[70] = {langN.show[strIS_CFAN_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[71] = {langN.show[strIS_CFAN_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[72] = {langN.show[strCompressor]+langN.show[strOpen],true};  //"空调压缩机开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[73] = {langN.show[strCompressor]+langN.show[strOpen],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[74] = {langN.show[strIS_CMPR_HT_STS]+langN.show[strOpen],true}; //"空调压缩机加热带开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[75] = {langN.show[strIS_CMPR_HT_STS]+langN.show[strOpen],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[76] = {langN.show[strIS_CMPR_HP_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[77] = {langN.show[strIS_CMPR_HP_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[78] = {langN.show[strHighPressureLock],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[79] = {langN.show[strHighPressureLock],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[80] = {langN.show[strLowPressureAlm],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[81] = {langN.show[strLowPressureAlm],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[82] = {langN.show[strLowPressureLock],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[83] = {langN.show[strLowPressureLock],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[84] = {langN.show[strIS_CMPR_EXSU_HT_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[85] = {langN.show[strIS_CMPR_EXSU_HT_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[86] = {langN.show[strIS_CMPR_EXSU_HTLK_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[87] = {langN.show[strIS_CMPR_EXSU_HTLK_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[88] = {langN.show[strIS_CMPR_F_ABN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[89] = {langN.show[strIS_CMPR_F_ABN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[90] = {langN.show[strIS_CMPR_F_ABNLK],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[91] = {langN.show[strIS_CMPR_F_ABNLK],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[92] = {langN.show[strIS_CMPR_HP_LMTF],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[93] = {langN.show[strIS_CMPR_HP_LMTF],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[94] = {langN.show[strIS_VFD_COMM_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[95] = {langN.show[strIS_VFD_COMM_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[96] = {langN.show[strIS_VFD_AVOI],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[97] = {langN.show[strIS_VFD_AVOI],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[98] = {langN.show[strIS_VFD_DVOI],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[99] = {langN.show[strIS_VFD_DVOI],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[100] = {langN.show[strIS_VFD_SVOI],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[101] = {langN.show[strIS_VFD_SVOI],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[102] = {langN.show[strIS_VFD_BAD_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[103] = {langN.show[strIS_VFD_BAD_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[104] = {langN.show[strIS_VFD_AVOV],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[105] = {langN.show[strIS_VFD_AVOV],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[106] = {langN.show[strIS_VFD_DVOV],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[107] = {langN.show[strIS_VFD_DVOV],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[108] = {langN.show[strIS_VFD_SVOV],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[109] = {langN.show[strIS_VFD_SVOV],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[110] = {langN.show[strIS_VFD_BUS_LV],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[111] = {langN.show[strIS_VFD_BUS_LV],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[112] = {langN.show[strIS_VFD_MOL],true};//空调电机过载（OL1）告警
    almDevLogString[eAlmDevAc].AlmDevLogID[113] = {langN.show[strIS_VFD_MOL],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[114] = {langN.show[strIS_VFD_OL],true};//空调变频器过载（OL2）告警
    almDevLogString[eAlmDevAc].AlmDevLogID[115] = {langN.show[strIS_VFD_OL],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[116] = {langN.show[strIS_VFD_SPI],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[117] = {langN.show[strIS_VFD_SPI],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[118] = {langN.show[strIS_VFD_SPO],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[119] = {langN.show[strIS_VFD_SPO],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[120] = {langN.show[strIS_VFD_REV_OT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[121] = {langN.show[strIS_VFD_REV_OT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[122] = {langN.show[strIS_VFD_INV_OT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[123] = {langN.show[strIS_VFD_INV_OT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[124] = {langN.show[strIS_VFD_485_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[125] = {langN.show[strIS_VFD_485_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[126] = {langN.show[strIS_VFD_IDTT_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[127] = {langN.show[strIS_VFD_IDTT_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[128] = {langN.show[strIS_VFD_EEPROM_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[129] = {langN.show[strIS_VFD_EEPROM_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[130] = {langN.show[strIS_VFD_ETH1],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[131] = {langN.show[strIS_VFD_ETH1],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[132] = {langN.show[strIS_VFD_ETH2],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[133] = {langN.show[strIS_VFD_ETH2],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[134] = {langN.show[strIS_VFD_DEU],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[135] = {langN.show[strIS_VFD_DEU],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[136] = {langN.show[strIS_VFD_STO],true};//空调失调故障（STo）告警
    almDevLogString[eAlmDevAc].AlmDevLogID[137] = {langN.show[strIS_VFD_STO],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[138] = {langN.show[strIS_VFD_LL],true};//空调欠载故障（LL）告警
    almDevLogString[eAlmDevAc].AlmDevLogID[139] = {langN.show[strIS_VFD_LL],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[140] = {langN.show[strHum]+langN.show[strOpen],true}; //"空调加湿器开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[141] = {langN.show[strHum]+langN.show[strOpen],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[142] = {langN.show[strHumidifierFault],true}; //"空调加湿器故障告警"
    almDevLogString[eAlmDevAc].AlmDevLogID[143] = {langN.show[strHumidifierFault],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[144] = {langN.show[strIS_HUMI_AHI_DTT_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[145] = {langN.show[strIS_HUMI_AHI_DTT_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[146] = {langN.show[strIS_HUMI_DWV_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[147] = {langN.show[strIS_HUMI_DWV_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[148] = {langN.show[strIS_HUMI_WFLWL_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[149] = {langN.show[strIS_HUMI_WFLWL_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[150] = {langN.show[strIS_HUMI_WLS_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[151] = {langN.show[strIS_HUMI_WLS_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[152] = {langN.show[strIS_HUMI_CWHWL_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[153] = {langN.show[strIS_HUMI_CWHWL_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[154] = {langN.show[strIS_EH_IW_STS]+langN.show[strOpen],true}; //"空调电极加湿进水阀开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[155] = {langN.show[strIS_EH_IW_STS]+langN.show[strOpen],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[156] = {langN.show[strIS_EH_OW_STS]+langN.show[strOpen],true};   //空调电极加湿排水阀开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[157] = {langN.show[strIS_EH_OW_STS]+langN.show[strOpen],false};  //空调电极加湿排水阀开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[158] = {langN.show[strIS_HPUMP_STS]+langN.show[strOpen],true};  //空调湿膜加湿循环水泵开启
    almDevLogString[eAlmDevAc].AlmDevLogID[159] = {langN.show[strIS_HPUMP_STS]+langN.show[strOpen],false}; //空调湿膜加湿循环水泵开启
    almDevLogString[eAlmDevAc].AlmDevLogID[160] = {langN.show[strIS_WFH_IWSV_STS]+langN.show[strOpen],true};   //空调湿膜加湿进水阀开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[161] = {langN.show[strIS_WFH_IWSV_STS]+langN.show[strOpen],false};  //空调湿膜加湿进水阀开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[162] = {langN.show[strHeater]+langN.show[strOpen],true};       //空调加热器开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[163] = {langN.show[strHeater]+langN.show[strOpen],false};      //空调加热器开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[164] = {langN.show[strHeater],true};     //空调加热器故障告警"
    almDevLogString[eAlmDevAc].AlmDevLogID[165] = {langN.show[strHeater],false};    //空调加热器故障告警"

    almDevLogString[eAlmDevAc].AlmDevLogID[166] = {langN.show[strIS_HEAT_PTT_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[167] = {langN.show[strIS_HEAT_PTT_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[168] = {langN.show[strIS_HEAT1]+langN.show[strOpen],true};  //"空调加热器1开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[169] = {langN.show[strIS_HEAT1]+langN.show[strOpen],false}; //"空调加热器1开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[160] = {langN.show[strIS_HEAT2]+langN.show[strOpen],true};  //"空调加热器2开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[171] = {langN.show[strIS_HEAT2]+langN.show[strOpen],false}; //"空调加热器2开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[172] = {langN.show[strIS_HEAT1_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[173] = {langN.show[strIS_HEAT1_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[174] = {langN.show[strIS_HEAT2_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[175] = {langN.show[strIS_HEAT2_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[176] = {langN.show[strIS_ITSD1_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[177] = {langN.show[strIS_ITSD1_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[178] = {langN.show[strIS_ITSD2_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[179] = {langN.show[strIS_ITSD2_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[180] = {langN.show[strIS_IHSD1_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[181] = {langN.show[strIS_IHSD1_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[182] = {langN.show[strIS_OTSD1_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[183] = {langN.show[strIS_OTSD1_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[184] = {langN.show[strIS_OTSD2_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[185] = {langN.show[strIS_OTSD2_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[186] = {langN.show[strIS_OTSD3_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[187] = {langN.show[strIS_OTSD3_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[188] = {langN.show[strIS_OHSD1_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[189] = {langN.show[strIS_OHSD1_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[190] = {langN.show[strIS_EXSU_TSD_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[191] = {langN.show[strIS_EXSU_TSD_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[192] = {langN.show[strIS_SUCT_TSD_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[193] = {langN.show[strIS_SUCT_TSD_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[194] = {langN.show[strIS_SUCT_PSD_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[195] = {langN.show[strIS_SUCT_PSD_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[196] = {langN.show[strIS_EXSU_PSD_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[197] = {langN.show[strIS_EXSU_PSD_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[198] = {langN.show[strIS_LEWYSD_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[199] = {langN.show[strIS_LEWYSD_FLT],false};
     //空调远程温湿度探头n(0)故障
    almDevLogString[eAlmDevAc].AlmDevLogID[200] = {langN.show[strIS_RTHSD0_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[201] = {langN.show[strIS_RTHSD0_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[202] = {langN.show[strIS_RTHSD1_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[203] = {langN.show[strIS_RTHSD1_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[204] = {langN.show[strIS_RTHSD2_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[205] = {langN.show[strIS_RTHSD2_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[206] = {langN.show[strIS_RTHSD3_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[207] = {langN.show[strIS_RTHSD3_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[208] = {langN.show[strIS_RTHSD4_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[209] = {langN.show[strIS_RTHSD4_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[210] = {langN.show[strIS_RTHSD5_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[211] = {langN.show[strIS_RTHSD5_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[212] = {langN.show[strIS_RTHSD6_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[213] = {langN.show[strIS_RTHSD6_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[214] = {langN.show[strIS_RTHSD7_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[215] = {langN.show[strIS_RTHSD7_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[216] = {langN.show[strIS_RTHSD8_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[217] = {langN.show[strIS_RTHSD8_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[218] = {langN.show[strIS_RTHSD9_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[219] = {langN.show[strIS_RTHSD9_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[220] = {langN.show[strIS_RTHSD10_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[221] = {langN.show[strIS_RTHSD10_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[222] = {langN.show[strIS_RTHSD11_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[223] = {langN.show[strIS_RTHSD11_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[224] = {langN.show[strIS_RTHSD12_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[225] = {langN.show[strIS_RTHSD12_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[226] = {langN.show[strIS_RTHSD13_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[227] = {langN.show[strIS_RTHSD13_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[228] = {langN.show[strIS_RTHSD14_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[229] = {langN.show[strIS_RTHSD14_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[230] = {langN.show[strIS_RTHSD15_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[231] = {langN.show[strIS_RTHSD15_FLT],false};
    //空调远程温湿度探头n(15)故障
    almDevLogString[eAlmDevAc].AlmDevLogID[232] = {langN.show[strIS_NET_COMM_FLT],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[233] = {langN.show[strIS_NET_COMM_FLT],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[234] = {langN.show[strIS_NET_ADDR_CNF],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[235] = {langN.show[strIS_NET_ADDR_CNF],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[236] = {langN.show[strIS_NET_SFVER_ERR],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[237] = {langN.show[strIS_NET_SFVER_ERR],false};
    //空调从机00离线
    almDevLogString[eAlmDevAc].AlmDevLogID[238] = {langN.show[strIS_NET_S00_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[239] = {langN.show[strIS_NET_S00_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[240] = {langN.show[strIS_NET_S01_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[241] = {langN.show[strIS_NET_S01_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[242] = {langN.show[strIS_NET_S02_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[243] = {langN.show[strIS_NET_S02_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[244] = {langN.show[strIS_NET_S03_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[245] = {langN.show[strIS_NET_S03_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[246] = {langN.show[strIS_NET_S04_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[247] = {langN.show[strIS_NET_S04_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[248] = {langN.show[strIS_NET_S05_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[249] = {langN.show[strIS_NET_S05_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[250] = {langN.show[strIS_NET_S06_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[251] = {langN.show[strIS_NET_S06_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[252] = {langN.show[strIS_NET_S07_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[253] = {langN.show[strIS_NET_S07_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[254] = {langN.show[strIS_NET_S08_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[255] = {langN.show[strIS_NET_S08_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[256] = {langN.show[strIS_NET_S09_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[257] = {langN.show[strIS_NET_S09_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[258] = {langN.show[strIS_NET_S10_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[259] = {langN.show[strIS_NET_S10_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[260] = {langN.show[strIS_NET_S11_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[261] = {langN.show[strIS_NET_S11_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[262] = {langN.show[strIS_NET_S12_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[263] = {langN.show[strIS_NET_S12_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[264] = {langN.show[strIS_NET_S13_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[265] = {langN.show[strIS_NET_S13_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[266] = {langN.show[strIS_NET_S14_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[267] = {langN.show[strIS_NET_S14_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[268] = {langN.show[strIS_NET_S15_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[269] = {langN.show[strIS_NET_S15_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[270] = {langN.show[strIS_NET_S16_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[271] = {langN.show[strIS_NET_S16_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[272] = {langN.show[strIS_NET_S17_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[273] = {langN.show[strIS_NET_S17_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[274] = {langN.show[strIS_NET_S18_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[275] = {langN.show[strIS_NET_S18_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[276] = {langN.show[strIS_NET_S19_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[277] = {langN.show[strIS_NET_S19_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[278] = {langN.show[strIS_NET_S20_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[279] = {langN.show[strIS_NET_S20_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[280] = {langN.show[strIS_NET_S21_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[281] = {langN.show[strIS_NET_S21_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[282] = {langN.show[strIS_NET_S22_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[283] = {langN.show[strIS_NET_S22_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[284] = {langN.show[strIS_NET_S23_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[285] = {langN.show[strIS_NET_S23_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[286] = {langN.show[strIS_NET_S24_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[287] = {langN.show[strIS_NET_S24_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[288] = {langN.show[strIS_NET_S25_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[289] = {langN.show[strIS_NET_S25_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[290] = {langN.show[strIS_NET_S26_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[291] = {langN.show[strIS_NET_S26_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[292] = {langN.show[strIS_NET_S27_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[293] = {langN.show[strIS_NET_S27_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[294] = {langN.show[strIS_NET_S28_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[295] = {langN.show[strIS_NET_S28_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[296] = {langN.show[strIS_NET_S29_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[297] = {langN.show[strIS_NET_S29_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[298] = {langN.show[strIS_NET_S30_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[299] = {langN.show[strIS_NET_S30_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[300] = {langN.show[strIS_NET_S31_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[301] = {langN.show[strIS_NET_S31_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[302] = {langN.show[strIS_NET_S32_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[303] = {langN.show[strIS_NET_S32_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[304] = {langN.show[strIS_NET_S33_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[305] = {langN.show[strIS_NET_S33_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[306] = {langN.show[strIS_NET_S34_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[307] = {langN.show[strIS_NET_S34_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[308] = {langN.show[strIS_NET_S35_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[309] = {langN.show[strIS_NET_S35_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[310] = {langN.show[strIS_NET_S36_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[311] = {langN.show[strIS_NET_S36_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[312] = {langN.show[strIS_NET_S37_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[313] = {langN.show[strIS_NET_S37_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[314] = {langN.show[strIS_NET_S38_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[315] = {langN.show[strIS_NET_S38_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[316] = {langN.show[strIS_NET_S39_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[317] = {langN.show[strIS_NET_S39_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[318] = {langN.show[strIS_NET_S40_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[319] = {langN.show[strIS_NET_S40_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[320] = {langN.show[strIS_NET_S41_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[321] = {langN.show[strIS_NET_S41_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[322] = {langN.show[strIS_NET_S42_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[323] = {langN.show[strIS_NET_S42_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[324] = {langN.show[strIS_NET_S43_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[325] = {langN.show[strIS_NET_S43_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[326] = {langN.show[strIS_NET_S44_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[327] = {langN.show[strIS_NET_S44_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[328] = {langN.show[strIS_NET_S45_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[329] = {langN.show[strIS_NET_S45_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[330] = {langN.show[strIS_NET_S46_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[331] = {langN.show[strIS_NET_S46_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[332] = {langN.show[strIS_NET_S47_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[333] = {langN.show[strIS_NET_S47_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[334] = {langN.show[strIS_NET_S48_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[335] = {langN.show[strIS_NET_S48_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[336] = {langN.show[strIS_NET_S49_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[337] = {langN.show[strIS_NET_S49_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[338] = {langN.show[strIS_NET_S50_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[339] = {langN.show[strIS_NET_S50_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[340] = {langN.show[strIS_NET_S51_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[341] = {langN.show[strIS_NET_S51_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[342] = {langN.show[strIS_NET_S52_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[343] = {langN.show[strIS_NET_S52_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[344] = {langN.show[strIS_NET_S53_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[345] = {langN.show[strIS_NET_S53_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[346] = {langN.show[strIS_NET_S54_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[347] = {langN.show[strIS_NET_S54_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[348] = {langN.show[strIS_NET_S55_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[349] = {langN.show[strIS_NET_S55_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[350] = {langN.show[strIS_NET_S56_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[351] = {langN.show[strIS_NET_S56_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[352] = {langN.show[strIS_NET_S57_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[353] = {langN.show[strIS_NET_S57_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[354] = {langN.show[strIS_NET_S58_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[355] = {langN.show[strIS_NET_S58_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[356] = {langN.show[strIS_NET_S59_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[357] = {langN.show[strIS_NET_S59_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[358] = {langN.show[strIS_NET_S60_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[359] = {langN.show[strIS_NET_S60_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[360] = {langN.show[strIS_NET_S61_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[361] = {langN.show[strIS_NET_S61_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[362] = {langN.show[strIS_NET_S62_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[363] = {langN.show[strIS_NET_S62_OFFLN],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[364] = {langN.show[strIS_NET_S63_OFFLN],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[365] = {langN.show[strIS_NET_S63_OFFLN],false};
    //空调从机63离线告警
    almDevLogString[eAlmDevAc].AlmDevLogID[366] = {langN.show[strIS_DI_EFAN_OL_1],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[367] = {langN.show[strIS_DI_EFAN_OL_1],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[368] = {langN.show[strIS_DI_EFAN_OL_2],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[369] = {langN.show[strIS_DI_EFAN_OL_2],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[370] = {langN.show[strIS_DI_EFAN_OL_3],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[371] = {langN.show[strIS_DI_EFAN_OL_3],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[372] = {langN.show[strIS_DI_HP_ONOFF]+langN.show[strOpen],true};  //"空调高压开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[373] = {langN.show[strIS_DI_HP_ONOFF]+langN.show[strOpen],false}; //"空调高压开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[374] = {langN.show[strIS_DI_LP_ONOFF]+langN.show[strOpen],true};  //"空调低压开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[375] = {langN.show[strIS_DI_LP_ONOFF]+langN.show[strOpen],false}; //"空调低压开启"
    almDevLogString[eAlmDevAc].AlmDevLogID[376] = {langN.show[strIS_DI_WFH_LWL],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[377] = {langN.show[strIS_DI_WFH_LWL],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[378] = {langN.show[strIS_DI_CL_HWL],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[379] = {langN.show[strIS_DI_CL_HWL],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[380] = {langN.show[strIS_DI_HEAT_OL],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[381] = {langN.show[strIS_DI_HEAT_OL],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[382] = {langN.show[strIS_DI_CFAN_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[383] = {langN.show[strIS_DI_CFAN_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[384] = {langN.show[strIS_DI_AF_LS],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[385] = {langN.show[strIS_DI_AF_LS],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[386] = {langN.show[strIS_DI_FLT_BLK],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[387] = {langN.show[strIS_DI_FLT_BLK],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[388] = {langN.show[strIS_DI_SMK_ALM],true};
    almDevLogString[eAlmDevAc].AlmDevLogID[389] = {langN.show[strIS_DI_SMK_ALM],false};
    almDevLogString[eAlmDevAc].AlmDevLogID[390] = {langN.show[strIS_DI_ON],true};  //"空调远程开机"
    almDevLogString[eAlmDevAc].AlmDevLogID[391] = {langN.show[strIS_DI_OFF],false}; //"空调远程关机"



    //温湿度 logID消息
    almDevLogString[eAlmDevThs].AlmDevLogID[0] =  {langN.show[langEnum::strCommFail],true};
    almDevLogString[eAlmDevThs].AlmDevLogID[1] =  {langN.show[langEnum::strCommFail],false};
    almDevLogString[eAlmDevThs].AlmDevLogID[2] =  {langN.show[langEnum::strHighTempAlm],true};
    almDevLogString[eAlmDevThs].AlmDevLogID[3] =  {langN.show[langEnum::strHighTempAlm],false};
    almDevLogString[eAlmDevThs].AlmDevLogID[4] =  {langN.show[langEnum::strLowTempAlm],true};
    almDevLogString[eAlmDevThs].AlmDevLogID[5] =  {langN.show[langEnum::strLowTempAlm],false};
    almDevLogString[eAlmDevThs].AlmDevLogID[6] =  {langN.show[langEnum::strHighHumAlm],true};
    almDevLogString[eAlmDevThs].AlmDevLogID[7] =  {langN.show[langEnum::strHighHumAlm],false};
    almDevLogString[eAlmDevThs].AlmDevLogID[8] =  {langN.show[langEnum::strLowHumAlm],true};
    almDevLogString[eAlmDevThs].AlmDevLogID[9] =  {langN.show[langEnum::strLowHumAlm],false};
    almDevLogString[eAlmDevThs].AlmDevLogID[10] = {langN.show[langEnum::strManuAdd],true};
    almDevLogString[eAlmDevThs].AlmDevLogID[11] = {langN.show[langEnum::strManuDel],true};

    //PDU logID消息
    almDevLogString[eAlmDevPdu].AlmDevLogID[0] =  {langN.show[langEnum::strCommFail],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[1] =  {langN.show[langEnum::strCommFail],false};
    almDevLogString[eAlmDevPdu].AlmDevLogID[2] =  {langN.show[langEnum::strCurrOver],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[3] =  {langN.show[langEnum::strCurrOver],false};
    almDevLogString[eAlmDevPdu].AlmDevLogID[4] =  {langN.show[langEnum::strCurrLow],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[5] =  {langN.show[langEnum::strCurrLow],false};
    almDevLogString[eAlmDevPdu].AlmDevLogID[6] =  {langN.show[langEnum::strVoltHgrUpLimitBr1],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[7] =  {langN.show[langEnum::strVoltHgrUpLimitBr1],false};
    almDevLogString[eAlmDevPdu].AlmDevLogID[8] =  {langN.show[langEnum::strVoltLwrLwLimitBr1],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[9] =  {langN.show[langEnum::strVoltLwrLwLimitBr1],false};
    almDevLogString[eAlmDevPdu].AlmDevLogID[10] = {langN.show[langEnum::strCurrHgrUpLimitBr1],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[11] = {langN.show[langEnum::strCurrHgrUpLimitBr1],false};
    almDevLogString[eAlmDevPdu].AlmDevLogID[12] = {langN.show[langEnum::strCurrLwrLwLimitBr1],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[13] = {langN.show[langEnum::strCurrLwrLwLimitBr1],false};
    almDevLogString[eAlmDevPdu].AlmDevLogID[14] = {langN.show[langEnum::strVoltHgrUpLimitBr2],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[15] = {langN.show[langEnum::strVoltHgrUpLimitBr2],false};
    almDevLogString[eAlmDevPdu].AlmDevLogID[16] = {langN.show[langEnum::strVoltLwrLwLimitBr2],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[17] = {langN.show[langEnum::strVoltLwrLwLimitBr2],false};
    almDevLogString[eAlmDevPdu].AlmDevLogID[18] = {langN.show[langEnum::strCurrHgrUpLimitBr2],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[19] = {langN.show[langEnum::strCurrHgrUpLimitBr2],false};
    almDevLogString[eAlmDevPdu].AlmDevLogID[20] = {langN.show[langEnum::strCurrLwrLwLimitBr2],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[21] = {langN.show[langEnum::strCurrLwrLwLimitBr2],false};
    almDevLogString[eAlmDevPdu].AlmDevLogID[22] = {langN.show[langEnum::strVoltHgrUpLimitBr3],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[23] = {langN.show[langEnum::strVoltHgrUpLimitBr3],false};
    almDevLogString[eAlmDevPdu].AlmDevLogID[24] = {langN.show[langEnum::strVoltLwrLwLimitBr3],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[25] = {langN.show[langEnum::strVoltLwrLwLimitBr3],false};
    almDevLogString[eAlmDevPdu].AlmDevLogID[26] = {langN.show[langEnum::strCurrHgrUpLimitBr3],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[27] = {langN.show[langEnum::strCurrHgrUpLimitBr3],false};
    almDevLogString[eAlmDevPdu].AlmDevLogID[28] = {langN.show[langEnum::strCurrLwrLwLimitBr3],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[29] = {langN.show[langEnum::strCurrLwrLwLimitBr3],false};
    almDevLogString[eAlmDevPdu].AlmDevLogID[30] = {langN.show[langEnum::strRlyOpenB1],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[31] = {langN.show[langEnum::strRlyCloseB1],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[32] = {langN.show[langEnum::strRlyOpenB2],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[33] = {langN.show[langEnum::strRlyCloseB2],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[34] = {langN.show[langEnum::strRlyOpenB3],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[35] = {langN.show[langEnum::strRlyCloseB3],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[36] = {langN.show[langEnum::strRlyOpenB4],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[37] = {langN.show[langEnum::strRlyCloseB4],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[38] = {langN.show[langEnum::strRlyOpenB5],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[39] = {langN.show[langEnum::strRlyCloseB5],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[40] = {langN.show[langEnum::strRlyOpenB6],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[41] = {langN.show[langEnum::strRlyCloseB6],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[42] = {langN.show[langEnum::strRlyOpenB7],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[43] = {langN.show[langEnum::strRlyCloseB7],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[44] = {langN.show[langEnum::strRlyOpenB8],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[45] = {langN.show[langEnum::strRlyCloseB8],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[46] = {langN.show[langEnum::strRlyOpenB9],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[47] = {langN.show[langEnum::strRlyCloseB9],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[48] = {langN.show[langEnum::strRlyOpenB10],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[49] = {langN.show[langEnum::strRlyCloseB10],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[50] = {langN.show[langEnum::strRlyOpenB11],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[51] = {langN.show[langEnum::strRlyCloseB11],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[52] = {langN.show[langEnum::strRlyOpenB12],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[53] = {langN.show[langEnum::strRlyCloseB12],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[54] = {langN.show[langEnum::strRlyOpenB13],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[55] = {langN.show[langEnum::strRlyCloseB13],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[56] = {langN.show[langEnum::strRlyOpenB14],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[57] = {langN.show[langEnum::strRlyCloseB14],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[58] = {langN.show[langEnum::strRlyOpenB15],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[59] = {langN.show[langEnum::strRlyCloseB15],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[60] = {langN.show[langEnum::strRlyOpenB16],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[61] = {langN.show[langEnum::strRlyCloseB16],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[62] = {langN.show[langEnum::strRlyOpenB17],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[63] = {langN.show[langEnum::strRlyCloseB17],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[64] = {langN.show[langEnum::strRlyOpenB18],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[65] = {langN.show[langEnum::strRlyCloseB18],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[66] = {langN.show[langEnum::strRlyOpenB19],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[67] = {langN.show[langEnum::strRlyCloseB19],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[68] = {langN.show[langEnum::strRlyOpenB20],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[69] = {langN.show[langEnum::strRlyCloseB20],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[70] = {langN.show[langEnum::strRlyOpenB21],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[71] = {langN.show[langEnum::strRlyCloseB21],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[72] = {langN.show[langEnum::strRlyOpenB22],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[73] = {langN.show[langEnum::strRlyCloseB22],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[74] = {langN.show[langEnum::strRlyOpenB23],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[75] = {langN.show[langEnum::strRlyCloseB23],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[76] = {langN.show[langEnum::strRlyOpenB24],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[77] = {langN.show[langEnum::strRlyCloseB24],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[78] = {langN.show[langEnum::strSDOpenBr1],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[79] = {langN.show[langEnum::strSDCloseBr1],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[80] = {langN.show[langEnum::strSDOpenBr2],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[81] = {langN.show[langEnum::strSDCloseBr2],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[82] = {langN.show[langEnum::strSDOpenBr3],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[83] = {langN.show[langEnum::strSDCloseBr3],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[84] = {langN.show[langEnum::strManuAdd],true};
    almDevLogString[eAlmDevPdu].AlmDevLogID[85] = {langN.show[langEnum::strManuDel],true};

    //水浸 logID消息
    almDevLogString[eAlmDevLeak].AlmDevLogID[0] = {langN.show[langEnum::strCommFail],true};
    almDevLogString[eAlmDevLeak].AlmDevLogID[1] = {langN.show[langEnum::strCommFail],false};
    almDevLogString[eAlmDevLeak].AlmDevLogID[2] = {langN.show[langEnum::strLeakage],true};
    almDevLogString[eAlmDevLeak].AlmDevLogID[3] = {langN.show[langEnum::strLeakage],false};
    almDevLogString[eAlmDevLeak].AlmDevLogID[4] = {langN.show[langEnum::strCabAbnor],true};
    almDevLogString[eAlmDevLeak].AlmDevLogID[5] = {langN.show[langEnum::strCabAbnor],false};
    almDevLogString[eAlmDevLeak].AlmDevLogID[6] = {langN.show[langEnum::strManuAdd],true};
    almDevLogString[eAlmDevLeak].AlmDevLogID[7] = {langN.show[langEnum::strManuDel],true};

    //短信 logID消息
    almDevLogString[eAlmDevSms].AlmDevLogID[0] = {langN.show[langEnum::strCommFail],true};
    almDevLogString[eAlmDevSms].AlmDevLogID[1] = {langN.show[langEnum::strCommFail],false};
    almDevLogString[eAlmDevSms].AlmDevLogID[2] = {langN.show[langEnum::strManuAdd],true};
    almDevLogString[eAlmDevSms].AlmDevLogID[3] = {langN.show[langEnum::strManuDel],true};

    //IT配电柜 logID消息
    almDevLogString[eAlmDevItPdc].AlmDevLogID[0] =   {langN.show[langEnum::strCommFail],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[1] =   {langN.show[langEnum::strCommFail],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[2] =   {langN.show[langEnum::strOverCurrBr1],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[3] =   {langN.show[langEnum::strOverCurrBr1],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[4] =   {langN.show[langEnum::strLowCurrBr1],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[5] =   {langN.show[langEnum::strLowCurrBr1],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[6] =   {langN.show[langEnum::strOverCurrBr2],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[7] =   {langN.show[langEnum::strOverCurrBr2],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[8] =   {langN.show[langEnum::strLowCurrBr2],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[9] =   {langN.show[langEnum::strLowCurrBr2],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[10] =  {langN.show[langEnum::strOverCurrBr3],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[11] =  {langN.show[langEnum::strOverCurrBr3],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[12] =  {langN.show[langEnum::strLowCurrBr3],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[13] =  {langN.show[langEnum::strLowCurrBr3],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[14] =  {langN.show[langEnum::strOverCurrBr4],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[15] =  {langN.show[langEnum::strOverCurrBr4],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[16] =  {langN.show[langEnum::strLowCurrBr4],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[17] =  {langN.show[langEnum::strLowCurrBr4],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[18] =  {langN.show[langEnum::strOverCurrBr5],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[19] =  {langN.show[langEnum::strOverCurrBr5],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[20] =  {langN.show[langEnum::strLowCurrBr5],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[21] =  {langN.show[langEnum::strLowCurrBr5],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[22] =  {langN.show[langEnum::strOverCurrBr6],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[23] =  {langN.show[langEnum::strOverCurrBr6],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[24] =  {langN.show[langEnum::strLowCurrBr6],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[25] =  {langN.show[langEnum::strLowCurrBr6],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[26] =  {langN.show[langEnum::strOverCurrBr7],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[27] =  {langN.show[langEnum::strOverCurrBr7],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[28] =  {langN.show[langEnum::strLowCurrBr7],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[29] =  {langN.show[langEnum::strLowCurrBr7],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[30] =  {langN.show[langEnum::strOverCurrBr8],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[31] =  {langN.show[langEnum::strOverCurrBr8],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[32] =  {langN.show[langEnum::strLowCurrBr8],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[33] =  {langN.show[langEnum::strLowCurrBr8],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[34] =  {langN.show[langEnum::strOverCurrBr9],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[35] =  {langN.show[langEnum::strOverCurrBr9],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[36] =  {langN.show[langEnum::strLowCurrBr9],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[37] =  {langN.show[langEnum::strLowCurrBr9],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[38] =  {langN.show[langEnum::strOverCurrBr10],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[39] =  {langN.show[langEnum::strOverCurrBr10],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[40] =  {langN.show[langEnum::strLowCurrBr10],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[41] =  {langN.show[langEnum::strLowCurrBr10],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[42] =  {langN.show[langEnum::strOverCurrBr11],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[43] =  {langN.show[langEnum::strOverCurrBr11],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[44] =  {langN.show[langEnum::strLowCurrBr11],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[45] =  {langN.show[langEnum::strLowCurrBr11],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[46] =  {langN.show[langEnum::strOverCurrBr12],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[47] =  {langN.show[langEnum::strOverCurrBr12],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[48] =  {langN.show[langEnum::strLowCurrBr12],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[49] =  {langN.show[langEnum::strLowCurrBr12],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[50] =  {langN.show[langEnum::strOverCurrBr13],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[51] =  {langN.show[langEnum::strOverCurrBr13],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[52] =  {langN.show[langEnum::strLowCurrBr13],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[53] =  {langN.show[langEnum::strLowCurrBr13],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[54] =  {langN.show[langEnum::strOverCurrBr14],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[55] =  {langN.show[langEnum::strOverCurrBr14],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[56] =  {langN.show[langEnum::strLowCurrBr14],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[57] =  {langN.show[langEnum::strLowCurrBr14],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[58] =  {langN.show[langEnum::strOverCurrBr15],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[59] =  {langN.show[langEnum::strOverCurrBr15],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[60] =  {langN.show[langEnum::strLowCurrBr15],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[61] =  {langN.show[langEnum::strLowCurrBr15],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[62] =  {langN.show[langEnum::strOverCurrBr16],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[63] =  {langN.show[langEnum::strOverCurrBr16],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[64] =  {langN.show[langEnum::strLowCurrBr16],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[65] =  {langN.show[langEnum::strLowCurrBr16],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[66] =  {langN.show[langEnum::strOverCurrBr17],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[67] =  {langN.show[langEnum::strOverCurrBr17],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[68] =  {langN.show[langEnum::strLowCurrBr17],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[69] =  {langN.show[langEnum::strLowCurrBr17],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[70] =  {langN.show[langEnum::strOverCurrBr18],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[71] =  {langN.show[langEnum::strOverCurrBr18],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[72] =  {langN.show[langEnum::strLowCurrBr18],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[73] =  {langN.show[langEnum::strLowCurrBr18],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[74] =  {langN.show[langEnum::strOverCurrBr19],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[75] =  {langN.show[langEnum::strOverCurrBr19],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[76] =  {langN.show[langEnum::strLowCurrBr19],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[77] =  {langN.show[langEnum::strLowCurrBr19],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[78] =  {langN.show[langEnum::strOverCurrBr20],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[79] =  {langN.show[langEnum::strOverCurrBr20],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[80] =  {langN.show[langEnum::strLowCurrBr20],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[81] =  {langN.show[langEnum::strLowCurrBr20],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[82] =  {langN.show[langEnum::strOverCurrBr21],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[83] =  {langN.show[langEnum::strOverCurrBr21],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[84] =  {langN.show[langEnum::strLowCurrBr21],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[85] =  {langN.show[langEnum::strLowCurrBr21],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[86] =  {langN.show[langEnum::strOverCurrBr22],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[87] =  {langN.show[langEnum::strOverCurrBr22],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[88] =  {langN.show[langEnum::strLowCurrBr22],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[89] =  {langN.show[langEnum::strLowCurrBr22],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[90] =  {langN.show[langEnum::strOverCurrBr23],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[91] =  {langN.show[langEnum::strOverCurrBr23],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[92] =  {langN.show[langEnum::strLowCurrBr23],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[93] =  {langN.show[langEnum::strLowCurrBr23],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[94] =  {langN.show[langEnum::strOverCurrBr24],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[95] =  {langN.show[langEnum::strOverCurrBr24],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[96] =  {langN.show[langEnum::strLowCurrBr24],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[97] =  {langN.show[langEnum::strLowCurrBr24],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[98] =  {langN.show[langEnum::strOverCurrBr25],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[99] =  {langN.show[langEnum::strOverCurrBr25],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[100] = {langN.show[langEnum::strLowCurrBr25],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[101] = {langN.show[langEnum::strLowCurrBr25],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[102] = {langN.show[langEnum::strOverCurrBr26],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[103] = {langN.show[langEnum::strOverCurrBr26],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[104] = {langN.show[langEnum::strLowCurrBr26],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[105] = {langN.show[langEnum::strLowCurrBr26],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[106] = {langN.show[langEnum::strOverCurrBr27],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[107] = {langN.show[langEnum::strOverCurrBr27],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[108] = {langN.show[langEnum::strLowCurrBr27],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[109] = {langN.show[langEnum::strLowCurrBr27],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[110] = {langN.show[langEnum::strOverCurrBr28],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[111] = {langN.show[langEnum::strOverCurrBr28],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[112] = {langN.show[langEnum::strLowCurrBr28],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[113] = {langN.show[langEnum::strLowCurrBr28],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[114] = {langN.show[langEnum::strOverCurrBr29],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[115] = {langN.show[langEnum::strOverCurrBr29],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[116] = {langN.show[langEnum::strLowCurrBr29],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[117] = {langN.show[langEnum::strLowCurrBr29],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[118] = {langN.show[langEnum::strOverCurrBr30],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[119] = {langN.show[langEnum::strOverCurrBr30],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[120] = {langN.show[langEnum::strLowCurrBr30],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[121] = {langN.show[langEnum::strLowCurrBr30],false};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[122] = {langN.show[langEnum::strManuAdd],true};
    almDevLogString[eAlmDevItPdc].AlmDevLogID[123] = {langN.show[langEnum::strManuDel],true};

    //电量仪 logID消息
    almDevLogString[eAlmDevMeter].AlmDevLogID[0] = {langN.show[langEnum::strCommFail],true};
    almDevLogString[eAlmDevMeter].AlmDevLogID[1] = {langN.show[langEnum::strCommFail],false};
    almDevLogString[eAlmDevMeter].AlmDevLogID[2] = {langN.show[langEnum::strManuAdd],true};
    almDevLogString[eAlmDevMeter].AlmDevLogID[3] = {langN.show[langEnum::strManuDel],true};

    //列头柜 logID消息
    almDevLogString[eAlmDevSpds].AlmDevLogID[0] = {langN.show[langEnum::strCommFail],true};
    almDevLogString[eAlmDevSpds].AlmDevLogID[1] = {langN.show[langEnum::strCommFail],false};
    almDevLogString[eAlmDevSpds].AlmDevLogID[2] = {langN.show[langEnum::strManuAdd],true};
    almDevLogString[eAlmDevSpds].AlmDevLogID[3] = {langN.show[langEnum::strManuDel],true};
    almDevLogString[eAlmDevSpds].AlmDevLogID[4] = {langN.show[langEnum::strAlm],true};
    almDevLogString[eAlmDevSpds].AlmDevLogID[5] = {langN.show[langEnum::strAlm],false};

    //干接点 logID消息 接线盒
    almDevLogString[eAlmDevDc].AlmDevLogID[0] = {langN.show[langEnum::strCommFail],true};
    almDevLogString[eAlmDevDc].AlmDevLogID[1] = {langN.show[langEnum::strCommFail],false};
    almDevLogString[eAlmDevDc].AlmDevLogID[2] = {langN.show[langEnum::strManuAdd],true};
    almDevLogString[eAlmDevDc].AlmDevLogID[3] = {langN.show[langEnum::strManuDel],true};
    almDevLogString[eAlmDevDc].AlmDevLogID[4] = {langN.show[langEnum::strFrtDoorOpen],true};
    almDevLogString[eAlmDevDc].AlmDevLogID[5] = {langN.show[langEnum::strFrtDoorClose],true};
    almDevLogString[eAlmDevDc].AlmDevLogID[6] = {langN.show[langEnum::strBckDoorOpen],true};
    almDevLogString[eAlmDevDc].AlmDevLogID[7] = {langN.show[langEnum::strBckDoorClose],true};

    almDevLogString[eAlmDevDc].AlmDevLogID[8] =  {langN.show[langEnum::strSmokeAlm],true};
    almDevLogString[eAlmDevDc].AlmDevLogID[9] =  {langN.show[langEnum::strSmokeAlm],false};
    almDevLogString[eAlmDevDc].AlmDevLogID[10] = {langN.show[langEnum::strIrAlm],true};
    almDevLogString[eAlmDevDc].AlmDevLogID[11] = {langN.show[langEnum::strIrAlm],false};
    almDevLogString[eAlmDevDc].AlmDevLogID[12] = {langN.show[langEnum::strIrTamper],true};
    almDevLogString[eAlmDevDc].AlmDevLogID[13] = {langN.show[langEnum::strIrTamper],false};
    almDevLogString[eAlmDevDc].AlmDevLogID[14] = {langN.show[langEnum::strLeakAlm],true};
    almDevLogString[eAlmDevDc].AlmDevLogID[15] = {langN.show[langEnum::strLeakAlm],false};
    almDevLogString[eAlmDevDc].AlmDevLogID[16] = {langN.show[langEnum::strFilterClog],true};
    almDevLogString[eAlmDevDc].AlmDevLogID[17] = {langN.show[langEnum::strFilterClog],false};
    almDevLogString[eAlmDevDc].AlmDevLogID[18] = {langN.show[langEnum::strDoorAlarm],true};
    almDevLogString[eAlmDevDc].AlmDevLogID[19] = {langN.show[langEnum::strDoorAlarm],false};
    almDevLogString[eAlmDevDc].AlmDevLogID[20] = {langN.show[langEnum::strDoorOpLongTimeAlm],true};
    almDevLogString[eAlmDevDc].AlmDevLogID[21] = {langN.show[langEnum::strDoorOpLongTimeAlm],false};
    almDevLogString[eAlmDevDc].AlmDevLogID[22] = {langN.show[langEnum::strIllegalDoor],true};
    almDevLogString[eAlmDevDc].AlmDevLogID[23] = {langN.show[langEnum::strIllegalDoor],false};


    //电池巡检仪 logID消息
    almDevLogString[eAlmDevBMS].AlmDevLogID[0] =  {langN.show[langEnum::strCommFail],true};
    almDevLogString[eAlmDevBMS].AlmDevLogID[1] =  {langN.show[langEnum::strCommFail],false};
    almDevLogString[eAlmDevBMS].AlmDevLogID[2] =  {langN.show[langEnum::strManuAdd],true};
    almDevLogString[eAlmDevBMS].AlmDevLogID[3] =  {langN.show[langEnum::strManuDel],true};
    almDevLogString[eAlmDevBMS].AlmDevLogID[4] =  {langN.show[langEnum::strBattPack1Alm],true};
    almDevLogString[eAlmDevBMS].AlmDevLogID[5] =  {langN.show[langEnum::strBattPack1Alm],false};
    almDevLogString[eAlmDevBMS].AlmDevLogID[6] =  {langN.show[langEnum::strBattPack2Alm],true};
    almDevLogString[eAlmDevBMS].AlmDevLogID[7] =  {langN.show[langEnum::strBattPack2Alm],false};
    almDevLogString[eAlmDevBMS].AlmDevLogID[8] =  {langN.show[langEnum::strBattPack3Alm],true};
    almDevLogString[eAlmDevBMS].AlmDevLogID[9] =  {langN.show[langEnum::strBattPack3Alm],false};
    almDevLogString[eAlmDevBMS].AlmDevLogID[10] = {langN.show[langEnum::strBattPack4Alm],true};
    almDevLogString[eAlmDevBMS].AlmDevLogID[11] = {langN.show[langEnum::strBattPack4Alm],false};

    //ATS logID消息
    almDevLogString[eAlmDevAts].AlmDevLogID[0] =  {langN.show[langEnum::strCommFail],true};
    almDevLogString[eAlmDevAts].AlmDevLogID[1] =  {langN.show[langEnum::strCommFail],false};
    almDevLogString[eAlmDevAts].AlmDevLogID[2] =  {langN.show[langEnum::strManuAdd],true};
    almDevLogString[eAlmDevAts].AlmDevLogID[3] =  {langN.show[langEnum::strManuDel],true};
    almDevLogString[eAlmDevAts].AlmDevLogID[4] =  {langN.show[langEnum::strAlm],true};
    almDevLogString[eAlmDevAts].AlmDevLogID[5] =  {langN.show[langEnum::strAlm],false};

    //新风机 logID消息
    almDevLogString[eAlmDevFan].AlmDevLogID[0] =  {langN.show[langEnum::strCommFail],true};
    almDevLogString[eAlmDevFan].AlmDevLogID[1] =  {langN.show[langEnum::strCommFail],false};
    almDevLogString[eAlmDevFan].AlmDevLogID[2] =  {langN.show[langEnum::strManuAdd],true};
    almDevLogString[eAlmDevFan].AlmDevLogID[3] =  {langN.show[langEnum::strManuDel],true};
    almDevLogString[eAlmDevFan].AlmDevLogID[4] =  {langN.show[langEnum::strHighTempAlm],true};
    almDevLogString[eAlmDevFan].AlmDevLogID[5] =  {langN.show[langEnum::strHighTempAlm],false};
    almDevLogString[eAlmDevFan].AlmDevLogID[6] =  {langN.show[langEnum::strHighHumAlm],true};
    almDevLogString[eAlmDevFan].AlmDevLogID[7] =  {langN.show[langEnum::strHighHumAlm],false};
    almDevLogString[eAlmDevFan].AlmDevLogID[8] =  {langN.show[langEnum::strAirFilterAlarm],true};
    almDevLogString[eAlmDevFan].AlmDevLogID[9] =  {langN.show[langEnum::strAirFilterAlarm],false};

    //

    //风扇控制器 logID消息
    almDevLogString[eAlmDevFanCtl].AlmDevLogID[0] =  {langN.show[langEnum::strCommFail],true};
    almDevLogString[eAlmDevFanCtl].AlmDevLogID[1] =  {langN.show[langEnum::strCommFail],false};
    almDevLogString[eAlmDevFanCtl].AlmDevLogID[2] =  {langN.show[langEnum::strManuAdd],true};
    almDevLogString[eAlmDevFanCtl].AlmDevLogID[3] =  {langN.show[langEnum::strManuDel],true};
    almDevLogString[eAlmDevFanCtl].AlmDevLogID[4] =  {langN.show[langEnum::strSD],true};
    almDevLogString[eAlmDevFanCtl].AlmDevLogID[5] =  {langN.show[langEnum::strSU],true};
    almDevLogString[eAlmDevFanCtl].AlmDevLogID[6] =  {langN.show[langEnum::strFault],true};
    almDevLogString[eAlmDevFanCtl].AlmDevLogID[7] =  {langN.show[langEnum::strFault],false};

    //PDS配电 logID消息
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[0] =   {langN.show[langEnum::strCommFail],true};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[1] =   {langN.show[langEnum::strCommFail],false};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[2] =   {langN.show[langEnum::strManuAdd],true};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[3] =   {langN.show[langEnum::strManuDel],true};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[4] =   {langN.show[langEnum::strAlm],true};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[5] =   {langN.show[langEnum::strAlm],false};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[6] =   {langN.show[langEnum::strMain]+" "+langN.show[langEnum::strVoltOvH],true};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[7] =   {langN.show[langEnum::strMain]+" "+langN.show[langEnum::strVoltOvH],false};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[8] =   {langN.show[langEnum::strMain]+" "+langN.show[langEnum::strVoltOvL],true};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[9] =   {langN.show[langEnum::strMain]+" "+langN.show[langEnum::strVoltOvL],false};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[10] =  {langN.show[langEnum::strMain]+" "+langN.show[langEnum::strPhFault],true};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[11] =  {langN.show[langEnum::strMain]+" "+langN.show[langEnum::strPhFault],false};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[12] =  {langN.show[langEnum::strMain]+" "+langN.show[langEnum::strOverCurr],true};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[13] =  {langN.show[langEnum::strMain]+" "+langN.show[langEnum::strOverCurr],false};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[14] =  {langN.show[langEnum::strMain]+" "+langN.show[langEnum::strLowCurr],true};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[15] =  {langN.show[langEnum::strMain]+" "+langN.show[langEnum::strLowCurr],false};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[16] =  {langN.show[langEnum::strMain]+" "+langN.show[langEnum::strFreqFault],true};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[17] =  {langN.show[langEnum::strMain]+" "+langN.show[langEnum::strFreqFault],false};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[18] =  {langN.show[langEnum::strBrh]+" "+langN.show[langEnum::strVoltOvH],true};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[19] =  {langN.show[langEnum::strBrh]+" "+langN.show[langEnum::strVoltOvH],false};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[20] =  {langN.show[langEnum::strBrh]+" "+langN.show[langEnum::strVoltOvL],true};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[21] =  {langN.show[langEnum::strBrh]+" "+langN.show[langEnum::strVoltOvL],false};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[22] =  {langN.show[langEnum::strBrh]+" "+langN.show[langEnum::strOverCurr],true};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[23] =  {langN.show[langEnum::strBrh]+" "+langN.show[langEnum::strOverCurr],false};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[24] =  {langN.show[langEnum::strBrh]+" "+langN.show[langEnum::strLowCurr],true};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[25] =  {langN.show[langEnum::strBrh]+" "+langN.show[langEnum::strLowCurr],false};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[26] =  {langN.show[langEnum::strBrh]+" "+langN.show[langEnum::strCutout],true};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[27] =  {langN.show[langEnum::strBrh]+" "+langN.show[langEnum::strShut],true};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[28] =  {langN.show[langEnum::strBrh]+" "+langN.show[langEnum::strHighTempAlm],true};
    almDevLogString[eAlmDevCtrlBox].AlmDevLogID[29] =  {langN.show[langEnum::strBrh]+" "+langN.show[langEnum::strHighTempAlm],false};

}

QString AlarmLogIDtoString(qint16 logid, ExtDevAlmEnum devName)
{
    QString devStr = "";
    bool devStatus = almDevLogString[devName].AlmDevLogID[logid].status;
    devStr = almDevLogString[devName].AlmDevLogID[logid].content;
    if(!devStr.isEmpty()){
        if(devStatus){
            devStr +="-"+langN.show[langEnum::strHappen];   //发生
        }else{
            devStr +="-"+langN.show[langEnum::strVanish];   //消失
        }
    }

    return devStr;
}

QString AlarmDevTypetoString(qint16 devtype)
{
    return  almDevTypeString.AlmDevType[devtype];
}
