#include "RatioStruct.h"
#include "gettext.h"
#include "language/languagePublic.h"
struct ExtDevRatioStruct extDevRatio;
struct ExtDevShowStruct  extDevShow;

void ExtDevRatioInit()
{
    //PUE系数
    extDevRatio.PUERatio = 0.01;
    //温湿度系数
    extDevRatio.eThsRatio[eThsParaTmp]       =  0.1;
    extDevRatio.eThsRatio[eThsParaHum]       =  0.1;
    extDevRatio.eThsRatio[eThsParaAlmSts]    =  1;
    extDevRatio.eThsRatio[eThsParaOutIO]     =  1;
    extDevRatio.eThsRatio[eThsParaTmpUpper]  =  0.1;
    extDevRatio.eThsRatio[eThsParaTmpLower]  =  0.1;
    extDevRatio.eThsRatio[eThsParaTmpAlmDiff] = 0.1;
    extDevRatio.eThsRatio[eThsParaHumUpper]  =  0.1;
    extDevRatio.eThsRatio[eThsParaHumLower]  =  0.1;
    extDevRatio.eThsRatio[eThsParaHumAlmDiff] = 0.1;

    //空调系数 单位 状态
    //所有状态默认 为正常和告警，其他值在这里重新赋值
    for(int i=0;i<eAcStsNum;++i){
        //显示
        extDevShow.eAcStsShow[i][0] = langN.show[langEnum::strNorm];    //正常
        extDevShow.eAcStsShow[i][1] = langN.show[langEnum::strAlm];    //告警
        //默认系数
        extDevRatio.eAcStsRatio[i]  = 1;

    }

    //状态值
    extDevShow.eAcStsShow[IS_ONOFF_STS][0] = langN.show[langEnum::strSD];   //关机
    extDevShow.eAcStsShow[IS_ONOFF_STS][1] = langN.show[langEnum::strSU];   //开机
    extDevShow.eAcStsShow[IS_LL_SV_STS][0] = langN.show[langEnum::strOff];   //关
    extDevShow.eAcStsShow[IS_LL_SV_STS][1] = langN.show[langEnum::strOn];   //开
    extDevShow.eAcStsShow[IS_CPUMP_STS][0] = langN.show[langEnum::strOff];
    extDevShow.eAcStsShow[IS_CPUMP_STS][1] = langN.show[langEnum::strOn];
    extDevShow.eAcStsShow[IS_EFAN_STS    ][0] = langN.show[langEnum::strOff];
    extDevShow.eAcStsShow[IS_EFAN_STS    ][1] = langN.show[langEnum::strOn];
    extDevShow.eAcStsShow[IS_CFAN_STS    ][0] = langN.show[langEnum::strOff];
    extDevShow.eAcStsShow[IS_CFAN_STS    ][1] = langN.show[langEnum::strOn];
    extDevShow.eAcStsShow[IS_CMPR_STS    ][0] = langN.show[langEnum::strOff];
    extDevShow.eAcStsShow[IS_CMPR_STS    ][1] = langN.show[langEnum::strOn];
    extDevShow.eAcStsShow[IS_CMPR_HT_STS ][0] = langN.show[langEnum::strOff];
    extDevShow.eAcStsShow[IS_CMPR_HT_STS ][1] = langN.show[langEnum::strOn];
    extDevShow.eAcStsShow[IS_HUMI_STS    ][0] = langN.show[langEnum::strOff];
    extDevShow.eAcStsShow[IS_HUMI_STS    ][1] = langN.show[langEnum::strOn];
    extDevShow.eAcStsShow[IS_EH_IW_STS   ][0] = langN.show[langEnum::strOff];
    extDevShow.eAcStsShow[IS_EH_IW_STS   ][1] = langN.show[langEnum::strOn];
    extDevShow.eAcStsShow[IS_EH_OW_STS   ][0] = langN.show[langEnum::strOff];
    extDevShow.eAcStsShow[IS_EH_OW_STS   ][1] = langN.show[langEnum::strOn];
    extDevShow.eAcStsShow[IS_HPUMP_STS   ][0] = langN.show[langEnum::strOff];
    extDevShow.eAcStsShow[IS_HPUMP_STS   ][1] = langN.show[langEnum::strOn];
    extDevShow.eAcStsShow[IS_WFH_IWSV_STS][0] = langN.show[langEnum::strOff];
    extDevShow.eAcStsShow[IS_WFH_IWSV_STS][1] = langN.show[langEnum::strOn];
    extDevShow.eAcStsShow[IS_HEAT_STS    ][0] = langN.show[langEnum::strOff];
    extDevShow.eAcStsShow[IS_HEAT_STS    ][1] = langN.show[langEnum::strOn];
    extDevShow.eAcStsShow[IS_HEAT1_STS   ][0] = langN.show[langEnum::strOff];
    extDevShow.eAcStsShow[IS_HEAT1_STS   ][1] = langN.show[langEnum::strOn];
    extDevShow.eAcStsShow[IS_HEAT2_STS   ][0] = langN.show[langEnum::strOff];
    extDevShow.eAcStsShow[IS_HEAT2_STS   ][1] = langN.show[langEnum::strOn];
    extDevShow.eAcStsShow[IS_DI_HP_ONOFF ][0] = langN.show[langEnum::strOff];
    extDevShow.eAcStsShow[IS_DI_HP_ONOFF ][1] = langN.show[langEnum::strOn];
    extDevShow.eAcStsShow[IS_DI_LP_ONOFF ][0] = langN.show[langEnum::strOff];
    extDevShow.eAcStsShow[IS_DI_LP_ONOFF ][1] = langN.show[langEnum::strOn];
    extDevShow.eAcStsShow[IS_DI_ONOFF    ][0] = langN.show[langEnum::strOff];
    extDevShow.eAcStsShow[IS_DI_ONOFF    ][1] = langN.show[langEnum::strOn];


    //------------------------para-----------------
    //默认系数
    for(int i=0;i<eAcParaNum;++i){
        extDevRatio.eAcParaRatio[i] = 1;
        extDevShow.eAcParaUnit[i] ="";
    }
    //可读写设置
    extDevRatio.eAcParaRatio[RU_ONOFF_CTL          ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_CTL_WAYS           ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_OTS_x10            ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RU_ITS_x10            ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RU_HS_x10             ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RU_AS_DLY             ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_AS_DLY_EN          ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_USER_CFG_CLN       ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_FLTL_CLEAR         ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_CLCTL_PR_x10       ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RU_HTCTL_PR_x10       ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RU_IAF_AHCTL_PR_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RU_IAF_DHCTL_PR_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RU_TCTL_DF_x10        ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RU_HCTL_DF_x10        ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RU_DATE_YY            ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_DATE_MM            ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_DATE_DD            ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_TIME_HH            ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_TIME_MM            ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_TIME_SS            ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_RMDBS_ADDR         ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_RMDBS_BAUD         ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_NET_EN             ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_NET_ADDR           ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_NET_NUMS           ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_NET_SW_NUMS        ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_NET_RTT_CYC        ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_NET_WK_NUMS        ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_NET_RQ_SYNC        ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_NET_OV_FUNC        ]              = 1   ;
    extDevRatio.eAcParaRatio[RU_NET_HT_ALLON       ]              = 1   ;
    extDevRatio.eAcParaRatio[RM_VACUMD_EN          ]              = 1   ;
    extDevRatio.eAcParaRatio[RM_MMD_EN             ]              = 1   ;
    extDevRatio.eAcParaRatio[RM_MMD_FANRS_CTL_x10  ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_MMD_ODM_CTL        ]              = 1   ;
    extDevRatio.eAcParaRatio[RM_MMD_HEAT_CTL       ]              = 1   ;
    extDevRatio.eAcParaRatio[RM_MMD_HUMI_CTL       ]              = 1   ;
    extDevRatio.eAcParaRatio[RM_MMD_INWSV_CTL      ]              = 1   ;
    extDevRatio.eAcParaRatio[RM_MMD_DEWSV_CTL      ]              = 1   ;
    extDevRatio.eAcParaRatio[RM_MMD_LLSV_CTL       ]              = 1   ;
    extDevRatio.eAcParaRatio[RM_MMD_CMPRF          ]              = 1   ;
    extDevRatio.eAcParaRatio[RM_MMD_EEV_OPEN_CTLMD ]              = 1   ;
    extDevRatio.eAcParaRatio[RM_MMD_EEV_OPEN       ]              = 1   ;
    extDevRatio.eAcParaRatio[RM_MMD_DBTM           ]              = 1   ;
    extDevRatio.eAcParaRatio[RM_AFV_CF_x100        ]              = 0.01;
    extDevRatio.eAcParaRatio[RM_CCP_CF_x100        ]              = 0.01;
    extDevRatio.eAcParaRatio[RM_ITSD1_CF_x10       ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_ITSD2_CF_x10       ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_OTSD1_CF_x10       ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_OTSD2_CF_x10       ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_OTSD3_CF_x10       ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_IHSD1_CF_x10       ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_OHSD1_CF_x10       ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_SUCTT_CF_x10       ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_EXSUT_CF_x10       ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_SUCTP_CF_x10       ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_EXSUP_CF_x10       ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_LEWY_CF_x10        ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_AHI_CF_x10         ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RTSD01_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RTSD02_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RTSD03_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RTSD04_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RTSD05_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RTSD06_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RTSD07_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RTSD08_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RTSD09_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RTSD10_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RTSD11_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RTSD12_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RTSD13_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RTSD14_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RTSD15_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RTSD16_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RHSD01_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RHSD02_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RHSD03_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RHSD04_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RHSD05_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RHSD06_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RHSD07_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RHSD08_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RHSD09_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RHSD10_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RHSD11_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RHSD12_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RHSD13_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RHSD14_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RHSD15_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_RHSD16_CF_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RM_SYS_WKTM_CLN       ]              = 1   ;
    extDevRatio.eAcParaRatio[RM_EFAN_WKTM_CLN      ]              = 1   ;
    extDevRatio.eAcParaRatio[RM_HUMI_WKTM_CLN      ]              = 1   ;
    extDevRatio.eAcParaRatio[RM_HEAT1_WKTM_CLN     ]              = 1   ;
    extDevRatio.eAcParaRatio[RM_HEAT2_WKTM_CLN     ]              = 1   ;
    extDevRatio.eAcParaRatio[RM_FLT_WKTM_CLN       ]              = 1   ;
    extDevRatio.eAcParaRatio[RM_ODM_WKTM_CLN       ]              = 1   ;
    extDevRatio.eAcParaRatio[RM_CPUMP_WKTM_CLN     ]              = 1   ;
    extDevRatio.eAcParaRatio[RM_CMPR_WKTM_CLN      ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_AC_MODEL           ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_REFRIG_TYPE        ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_T_CALC_WAYS        ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_EFAN_CTL_WAYS      ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_CTL_CYC            ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_PRT_CYC            ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_EFAN_FLT_MNTNTM    ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_LEWY_CTL_x10       ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_DH_LEWY_CF_x10     ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_LEWYCTL_CF_x10     ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CPUMP_MIN_WKTM     ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_WFWV_ON_TM         ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_WFWV_OFF_TM        ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_DHLT_LMT_DF_x10    ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_IDM_AFV_DISP_EN    ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_SYS_CCP_DISP_EN    ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_CLAHMD_EN          ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_DHCTL_EN           ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_DEV_EN1            ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_DEV_EN2            ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_DEV_EN3            ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_IT_OH_x10          ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_IT_OL_x10          ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_OT_OH_x10          ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_OT_OL_x10          ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_H_OH_x10           ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_H_OL_x10           ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_HPFLT_SET_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_LPFLT_SET_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_LLCL_EN            ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_PRT_MIN_TM         ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_CMPR_ON_TM         ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_CMPR_OFF_TM1       ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_CMPR_OFF_TM2       ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_CLMD_INND_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CLCMPR_OFFND_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_EXSU_HPPRT_x10]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_SUCT_LPPRT_x10]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_IPM_PRTT_x10  ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_VFD_PRTI_x10  ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_EXSU_HT_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_PAHP_PC1_x10  ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_PAHP_PC2_x10  ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_PAHP_PC3_x10  ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_PAHP_PC4_x10  ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_PAHP_PC5_x10  ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_PDF_MUL_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_MINR_TM       ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_CMPR_MINS_TM       ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_CMPR_STLP_DLY      ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_CMPR_LPPRT_DLY     ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_CMPR_SSTEP_F_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_SHOLD_F_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_DWFPRT_F_x10  ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_SHOLD_TM      ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_CMPR_VFD_STEP_x10  ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_VFD_REOF_x10  ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_REO_RISKF_x10 ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_CMPL_REOTM    ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_CMPR_CP_x10        ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_CI_x10        ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_HP_x10        ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_HI_x10        ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_PAP           ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_CMPR_PAI           ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_CMPR_CTL_CYC       ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_CMPR_RATE_F_x10    ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_MIN_F_x10     ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_CRS_NC1_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_CRS_NC2_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_CRS_NC3_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_CRS_NC4_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_CRS_NC5_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_CRS_NC6_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_RESN1_H_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_RESN1_L_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_RESN2_H_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_RESN2_L_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_RESN3_H_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_RESN3_L_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_RESN4_H_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_RESN4_L_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_RESN5_H_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_CMPR_RESN5_L_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_VFD_AVTM           ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_VFD_DVTM           ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_VFD_MAX_F_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_VFD_MIN_F_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_EFAN_UPSPEED_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_EFAN_NUM           ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_EFAN_GRPS          ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_EFAN_RATE_RS_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_EFAN_MIN_RS_x10    ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_EFAN_CTL_CYC       ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_EFAN_RSP_x10       ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_EFAN_RSI_x10       ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_EFAN_CIOT_DF_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_EFAN_HIOT_DF_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_EFAN_IOT_AQ_CYC    ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_EFAN_ON_DLY        ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_EEV_MAX_OPEN       ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_EEV_MIN_OPEN       ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_EEV_CTL_CYC        ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_EEV_INIT_OPEN      ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_EEV_BLNC_OPEN      ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_EEV_BLNC_TM        ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_EEV_INIT_TM        ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_EEV_OFF_DLY        ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_EEV_ET_MOP_x10     ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_EEV_MOPP_x10       ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_EEV_MOPI_x10       ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_EEV_KPC_x10        ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_EEV_TIC_x10        ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_EEV_CSSHT_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_EEV_HSSHT_x10      ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_HUMI_TYPE          ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HUMI_INH_KG_x10    ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_HUMI_IPV           ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HUMI_IPPS          ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HUMI_INH_PHTI      ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HUMI_INH_PHTTM     ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HUMI_INH_INWI      ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HUMI_INH_INWSI     ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HUMI_INH_DEWI      ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HUMI_NDEWI         ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HUMI_MIN_DEWTM     ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HUMI_DEW_TIMS      ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HUMI_SBDEM_CYC     ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HUMI_DEM_TM        ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HUMI_WKDEM_CYC     ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HUMI_HWTV          ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HUMI_HWDF          ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HUMI_CLN_TIMS      ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HEAT_CLASS         ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HEATCLASS1_UP_x10  ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_HEATCLASS1_DF_x10  ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_HEATCLASS2_UP_x10  ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_HEATCLASS2_DF_x10  ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_HEATCLASS3_UP_x10  ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_HEATCLASS3_DF_x10  ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_PHAS_SERR_ALW      ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_IPW_VOL            ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_IPW_VOH            ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_IPW_VDF            ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_IPW_FOL            ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_IPW_FOH            ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_IPW_PHAV_UNB_x10   ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_IPW_PHAV_UNBDF_x10 ]              = 0.1 ;
    extDevRatio.eAcParaRatio[RF_HISALM_CLN         ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_ALL_CFG_CLN        ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_EFAN1_ALM_EN       ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_EFAN2_ALM_EN       ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_EFAN3_ALM_EN       ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_AF_LOST_ALM_EN     ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_V_OL_ALM_EN        ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_V_OH_ALM_EN        ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_F_ABN_ALM_EN       ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_PHAS_LOS_ALM_EN    ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_PHAS_UNB_ALM_EN    ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_PHAS_SERR_ALM_EN   ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_P_OH_ALM_EN        ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_P_OL_ALM_EN        ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_TP_OH_ALM_EN       ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_TI_OH_ALM_EN       ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_TI_OL_ALM_EN       ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HI_OH_ALM_EN       ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HI_OL_ALM_EN       ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_TO_OH_ALM_EN       ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_TO_OL_ALM_EN       ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HEAT_ALM_EN        ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_SMOK_ALM_EN        ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_FSD_ALM_EN         ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_FLT_ALM_EN         ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_HUMI_PRT_ALM_EN    ]              = 1   ;
    extDevRatio.eAcParaRatio[RF_SYSDW_ALM_EN       ]              = 1   ;

//DIO功能设置   默认系数 默认单位

    extDevShow.eAcParaUnit[RU_OTS_x10              ]              = "℃";
    extDevShow.eAcParaUnit[RU_ITS_x10              ]              = "℃";
    extDevShow.eAcParaUnit[RU_HS_x10               ]              = "%";
    extDevShow.eAcParaUnit[RU_AS_DLY               ]              = "S";
    extDevShow.eAcParaUnit[RU_CLCTL_PR_x10         ]              = "℃";
    extDevShow.eAcParaUnit[RU_HTCTL_PR_x10         ]              = "℃";
    extDevShow.eAcParaUnit[RU_IAF_AHCTL_PR_x10     ]              = "%";
    extDevShow.eAcParaUnit[RU_IAF_DHCTL_PR_x10     ]              = "%";
    extDevShow.eAcParaUnit[RU_TCTL_DF_x10          ]              = "℃";
    extDevShow.eAcParaUnit[RU_HCTL_DF_x10          ]              = "%";
    extDevShow.eAcParaUnit[RU_DATE_YY              ]              = "";
    extDevShow.eAcParaUnit[RU_DATE_MM              ]              = "";
    extDevShow.eAcParaUnit[RU_DATE_DD              ]              = "";
    extDevShow.eAcParaUnit[RU_TIME_HH              ]              = "H";
    extDevShow.eAcParaUnit[RU_TIME_MM              ]              = "M";
    extDevShow.eAcParaUnit[RU_TIME_SS              ]              = "S";
    extDevShow.eAcParaUnit[RU_NET_RTT_CYC          ]              = "H";
    extDevShow.eAcParaUnit[RM_MMD_FANRS_CTL_x10    ]              = "%";
    extDevShow.eAcParaUnit[RM_MMD_CMPRF            ]              = "Hz";
    extDevShow.eAcParaUnit[RM_MMD_DBTM             ]              = "M";
    extDevShow.eAcParaUnit[RM_ITSD1_CF_x10         ]              = "℃";
    extDevShow.eAcParaUnit[RM_ITSD2_CF_x10         ]              = "℃";
    extDevShow.eAcParaUnit[RM_OTSD1_CF_x10         ]              = "℃";
    extDevShow.eAcParaUnit[RM_OTSD2_CF_x10         ]              = "℃";
    extDevShow.eAcParaUnit[RM_OTSD3_CF_x10         ]              = "℃";
    extDevShow.eAcParaUnit[RM_IHSD1_CF_x10         ]              = "%";
    extDevShow.eAcParaUnit[RM_OHSD1_CF_x10         ]              = "%";
    extDevShow.eAcParaUnit[RM_SUCTT_CF_x10         ]              = "℃";
    extDevShow.eAcParaUnit[RM_EXSUT_CF_x10         ]              = "℃";
    extDevShow.eAcParaUnit[RM_SUCTP_CF_x10         ]              = "bar";
    extDevShow.eAcParaUnit[RM_EXSUP_CF_x10         ]              = "bar";
    extDevShow.eAcParaUnit[RM_LEWY_CF_x10          ]              = "Pa";
    extDevShow.eAcParaUnit[RM_AHI_CF_x10           ]              = "A";
    extDevShow.eAcParaUnit[RM_RTSD01_CF_x10        ]              = "℃";
    extDevShow.eAcParaUnit[RM_RTSD02_CF_x10        ]              = "℃";
    extDevShow.eAcParaUnit[RM_RTSD03_CF_x10        ]              = "℃";
    extDevShow.eAcParaUnit[RM_RTSD04_CF_x10        ]              = "℃";
    extDevShow.eAcParaUnit[RM_RTSD05_CF_x10        ]              = "℃";
    extDevShow.eAcParaUnit[RM_RTSD06_CF_x10        ]              = "℃";
    extDevShow.eAcParaUnit[RM_RTSD07_CF_x10        ]              = "℃";
    extDevShow.eAcParaUnit[RM_RTSD08_CF_x10        ]              = "℃";
    extDevShow.eAcParaUnit[RM_RTSD09_CF_x10        ]              = "℃";
    extDevShow.eAcParaUnit[RM_RTSD10_CF_x10        ]              = "℃";
    extDevShow.eAcParaUnit[RM_RTSD11_CF_x10        ]              = "℃";
    extDevShow.eAcParaUnit[RM_RTSD12_CF_x10        ]              = "℃";
    extDevShow.eAcParaUnit[RM_RTSD13_CF_x10        ]              = "℃";
    extDevShow.eAcParaUnit[RM_RTSD14_CF_x10        ]              = "℃";
    extDevShow.eAcParaUnit[RM_RTSD15_CF_x10        ]              = "℃";
    extDevShow.eAcParaUnit[RM_RTSD16_CF_x10        ]              = "℃";
    extDevShow.eAcParaUnit[RM_RHSD01_CF_x10        ]              = "%";
    extDevShow.eAcParaUnit[RM_RHSD02_CF_x10        ]              = "%";
    extDevShow.eAcParaUnit[RM_RHSD03_CF_x10        ]              = "%";
    extDevShow.eAcParaUnit[RM_RHSD04_CF_x10        ]              = "%";
    extDevShow.eAcParaUnit[RM_RHSD05_CF_x10        ]              = "%";
    extDevShow.eAcParaUnit[RM_RHSD06_CF_x10        ]              = "%";
    extDevShow.eAcParaUnit[RM_RHSD07_CF_x10        ]              = "%";
    extDevShow.eAcParaUnit[RM_RHSD08_CF_x10        ]              = "%";
    extDevShow.eAcParaUnit[RM_RHSD09_CF_x10        ]              = "%";
    extDevShow.eAcParaUnit[RM_RHSD10_CF_x10        ]              = "%";
    extDevShow.eAcParaUnit[RM_RHSD11_CF_x10        ]              = "%";
    extDevShow.eAcParaUnit[RM_RHSD12_CF_x10        ]              = "%";
    extDevShow.eAcParaUnit[RM_RHSD13_CF_x10        ]              = "%";
    extDevShow.eAcParaUnit[RM_RHSD14_CF_x10        ]              = "%";
    extDevShow.eAcParaUnit[RM_RHSD15_CF_x10        ]              = "%";
    extDevShow.eAcParaUnit[RM_RHSD16_CF_x10        ]              = "%";
    extDevShow.eAcParaUnit[RF_CTL_CYC              ]              = "S";
    extDevShow.eAcParaUnit[RF_PRT_CYC              ]              = "S";
    extDevShow.eAcParaUnit[RF_EFAN_FLT_MNTNTM      ]              = "S";
    extDevShow.eAcParaUnit[RF_LEWY_CTL_x10         ]              = "Pa";
    extDevShow.eAcParaUnit[RF_DH_LEWY_CF_x10       ]              = "%";
    extDevShow.eAcParaUnit[RF_LEWYCTL_CF_x10       ]              = "Pa";
    extDevShow.eAcParaUnit[RF_CPUMP_MIN_WKTM       ]              = "S";
    extDevShow.eAcParaUnit[RF_WFWV_ON_TM           ]              = "S";
    extDevShow.eAcParaUnit[RF_WFWV_OFF_TM          ]              = "S";
    extDevShow.eAcParaUnit[RF_DHLT_LMT_DF_x10      ]              = "℃";
    extDevShow.eAcParaUnit[RF_IT_OH_x10            ]              = "℃";
    extDevShow.eAcParaUnit[RF_IT_OL_x10            ]              = "℃";
    extDevShow.eAcParaUnit[RF_OT_OH_x10            ]              = "℃";
    extDevShow.eAcParaUnit[RF_OT_OL_x10            ]              = "℃";
    extDevShow.eAcParaUnit[RF_H_OH_x10             ]              = "%";
    extDevShow.eAcParaUnit[RF_H_OL_x10             ]              = "%";
    extDevShow.eAcParaUnit[RF_HPFLT_SET_x10        ]              = "Pa";
    extDevShow.eAcParaUnit[RF_LPFLT_SET_x10        ]              = "Pa";
    extDevShow.eAcParaUnit[RF_PRT_MIN_TM           ]              = "M";
    extDevShow.eAcParaUnit[RF_CMPR_ON_TM           ]              = "M";
    extDevShow.eAcParaUnit[RF_CMPR_OFF_TM1         ]              = "M";
    extDevShow.eAcParaUnit[RF_CMPR_OFF_TM2         ]              = "M";
    extDevShow.eAcParaUnit[RF_CLMD_INND_x10        ]              = "%";
    extDevShow.eAcParaUnit[RF_CLCMPR_OFFND_x10     ]              = "%";
    extDevShow.eAcParaUnit[RF_CMPR_EXSU_HPPRT_x10  ]              = "bar";
    extDevShow.eAcParaUnit[RF_CMPR_SUCT_LPPRT_x10  ]              = "bar";
    extDevShow.eAcParaUnit[RF_CMPR_IPM_PRTT_x10    ]              = "℃";
    extDevShow.eAcParaUnit[RF_CMPR_VFD_PRTI_x10    ]              = "A";
    extDevShow.eAcParaUnit[RF_CMPR_EXSU_HT_x10     ]              = "℃";
    extDevShow.eAcParaUnit[RF_CMPR_PAHP_PC1_x10    ]              = "bar";
    extDevShow.eAcParaUnit[RF_CMPR_PAHP_PC2_x10    ]              = "bar";
    extDevShow.eAcParaUnit[RF_CMPR_PAHP_PC3_x10    ]              = "bar";
    extDevShow.eAcParaUnit[RF_CMPR_PAHP_PC4_x10    ]              = "bar";
    extDevShow.eAcParaUnit[RF_CMPR_PAHP_PC5_x10    ]              = "bar";
    extDevShow.eAcParaUnit[RF_CMPR_MINR_TM         ]              = "S";
    extDevShow.eAcParaUnit[RF_CMPR_MINS_TM         ]              = "S";
    extDevShow.eAcParaUnit[RF_CMPR_STLP_DLY        ]              = "S";
    extDevShow.eAcParaUnit[RF_CMPR_LPPRT_DLY       ]              = "S";
    extDevShow.eAcParaUnit[RF_CMPR_SSTEP_F_x10     ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_SHOLD_F_x10     ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_DWFPRT_F_x10    ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_SHOLD_TM        ]              = "S";
    extDevShow.eAcParaUnit[RF_CMPR_VFD_STEP_x10    ]              = "Hz/s";
    extDevShow.eAcParaUnit[RF_CMPR_VFD_REOF_x10    ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_REO_RISKF_x10   ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_CMPL_REOTM      ]              = "S";
    extDevShow.eAcParaUnit[RF_CMPR_CTL_CYC         ]              = "S";
    extDevShow.eAcParaUnit[RF_CMPR_RATE_F_x10      ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_MIN_F_x10       ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_CRS_NC1_x10     ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_CRS_NC2_x10     ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_CRS_NC3_x10     ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_CRS_NC4_x10     ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_CRS_NC5_x10     ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_CRS_NC6_x10     ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_RESN1_H_x10     ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_RESN1_L_x10     ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_RESN2_H_x10     ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_RESN2_L_x10     ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_RESN3_H_x10     ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_RESN3_L_x10     ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_RESN4_H_x10     ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_RESN4_L_x10     ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_RESN5_H_x10     ]              = "Hz";
    extDevShow.eAcParaUnit[RF_CMPR_RESN5_L_x10     ]              = "Hz";
    extDevShow.eAcParaUnit[RF_VFD_AVTM             ]              = "S";
    extDevShow.eAcParaUnit[RF_VFD_DVTM             ]              = "S";
    extDevShow.eAcParaUnit[RF_VFD_MAX_F_x10        ]              = "Hz";
    extDevShow.eAcParaUnit[RF_VFD_MIN_F_x10        ]              = "Hz";
    extDevShow.eAcParaUnit[RF_EFAN_UPSPEED_x10     ]              = "%";
    extDevShow.eAcParaUnit[RF_EFAN_RATE_RS_x10     ]              = "%";
    extDevShow.eAcParaUnit[RF_EFAN_MIN_RS_x10      ]              = "%";
    extDevShow.eAcParaUnit[RF_EFAN_CTL_CYC         ]              = "S";
    extDevShow.eAcParaUnit[RF_EFAN_CIOT_DF_x10     ]              = "℃";
    extDevShow.eAcParaUnit[RF_EFAN_HIOT_DF_x10     ]              = "℃";
    extDevShow.eAcParaUnit[RF_EFAN_IOT_AQ_CYC      ]              = "S";
    extDevShow.eAcParaUnit[RF_EFAN_ON_DLY          ]              = "S";
    extDevShow.eAcParaUnit[RF_EEV_CTL_CYC          ]              = "S";
    extDevShow.eAcParaUnit[RF_EEV_BLNC_TM          ]              = "S";
    extDevShow.eAcParaUnit[RF_EEV_INIT_TM          ]              = "S";
    extDevShow.eAcParaUnit[RF_EEV_OFF_DLY          ]              = "S";
    extDevShow.eAcParaUnit[RF_EEV_ET_MOP_x10       ]              = "℃";
    extDevShow.eAcParaUnit[RF_EEV_CSSHT_x10        ]              = "℃";
    extDevShow.eAcParaUnit[RF_EEV_HSSHT_x10        ]              = "℃";
    extDevShow.eAcParaUnit[RF_HUMI_INH_KG_x10      ]              = "Kg/h";
    extDevShow.eAcParaUnit[RF_HUMI_IPV             ]              = "V";
    extDevShow.eAcParaUnit[RF_HUMI_INH_PHTI        ]              = "%";
    extDevShow.eAcParaUnit[RF_HUMI_INH_PHTTM       ]              = "S";
    extDevShow.eAcParaUnit[RF_HUMI_INH_INWI        ]              = "%";
    extDevShow.eAcParaUnit[RF_HUMI_INH_INWSI       ]              = "%";
    extDevShow.eAcParaUnit[RF_HUMI_INH_DEWI        ]              = "%";
    extDevShow.eAcParaUnit[RF_HUMI_NDEWI           ]              = "%";
    extDevShow.eAcParaUnit[RF_HUMI_MIN_DEWTM       ]              = "S";
    extDevShow.eAcParaUnit[RF_HUMI_SBDEM_CYC       ]              = "H";
    extDevShow.eAcParaUnit[RF_HUMI_DEM_TM          ]              = "S";
    extDevShow.eAcParaUnit[RF_HUMI_WKDEM_CYC       ]              = "M";
    extDevShow.eAcParaUnit[RF_HUMI_HWTV            ]              = "V";
    extDevShow.eAcParaUnit[RF_HUMI_HWDF            ]              = "V";
    extDevShow.eAcParaUnit[RF_HEATCLASS1_UP_x10    ]              = "℃";
    extDevShow.eAcParaUnit[RF_HEATCLASS1_DF_x10    ]              = "℃";
    extDevShow.eAcParaUnit[RF_HEATCLASS2_UP_x10    ]              = "℃";
    extDevShow.eAcParaUnit[RF_HEATCLASS2_DF_x10    ]              = "℃";
    extDevShow.eAcParaUnit[RF_HEATCLASS3_UP_x10    ]              = "℃";
    extDevShow.eAcParaUnit[RF_HEATCLASS3_DF_x10    ]              = "℃";
    extDevShow.eAcParaUnit[RF_IPW_VOL              ]              = "V";
    extDevShow.eAcParaUnit[RF_IPW_VOH              ]              = "V";
    extDevShow.eAcParaUnit[RF_IPW_VDF              ]              = "V";
    extDevShow.eAcParaUnit[RF_IPW_FOL              ]              = "Hz";
    extDevShow.eAcParaUnit[RF_IPW_FOH              ]              = "Hz";
    extDevShow.eAcParaUnit[RF_IPW_PHAV_UNB_x10     ]              = "%";
    extDevShow.eAcParaUnit[RF_IPW_PHAV_UNBDF_x10   ]              = "%";



    //只读模拟量

    //只读模拟量中的状态量
//    extDevShow.eAcParaShow[IR_CTL_WAYS_STS][0]      = langN.show[langEnum::strReturnAirMode];//"回风控制";
//    extDevShow.eAcParaShow[IR_CTL_WAYS_STS][1]      = langN.show[langEnum::strCoolingMode];//"送风控制";

//    extDevShow.eAcParaShow[IR_SYS_RUN_STS_STS][0]      = langN.show[langEnum::strSD]; //"关机";
//    extDevShow.eAcParaShow[IR_SYS_RUN_STS_STS][1]      = langN.show[langEnum::strNormalSU]; //正常开机
//    extDevShow.eAcParaShow[IR_SYS_RUN_STS_STS][2]      = langN.show[langEnum::strFailtSD];  //故障关机
//    extDevShow.eAcParaShow[IR_SYS_RUN_STS_STS][3]      = langN.show[langEnum::strGroupStandby]; //群祖待机

//    extDevShow.eAcParaShow[IR_SYS_RUN_MOD_STS][0]      = langN.show[langEnum::strIdleMode]; //"空闲模式";
//    extDevShow.eAcParaShow[IR_SYS_RUN_MOD_STS][1]      = langN.show[langEnum::strCoolMode]; //"制冷模式";
//    extDevShow.eAcParaShow[IR_SYS_RUN_MOD_STS][2]      = langN.show[langEnum::strDehumidifMode]; //"除湿模式";
//    extDevShow.eAcParaShow[IR_SYS_RUN_MOD_STS][4]      = langN.show[langEnum::strHeatMode]; //"加热模式";
//    extDevShow.eAcParaShow[IR_SYS_RUN_MOD_STS][8]      = langN.show[langEnum::strHumidifMode]; //"加湿模式";
//    extDevShow.eAcParaShow[IR_SYS_RUN_MOD_STS][9]      = langN.show[langEnum::strCoolHumMode]; //"制冷加湿模式";
//    extDevShow.eAcParaShow[IR_SYS_RUN_MOD_STS][12]     = langN.show[langEnum::strHeatHumMode]; //"加热加湿模式";
//    extDevShow.eAcParaShow[IR_SYS_RUN_MOD_STS][6]      = langN.show[langEnum::strHeatDehumMode]; //"加热除湿模式";
//    extDevShow.eAcParaShow[IR_SYS_RUN_MOD_STS][10]     = langN.show[langEnum::strCoolingMode]; //"送风模式";



    extDevRatio.eAcParaRatio[IR_T_x10             ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_H_x10             ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_TS_x10            ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_HS_x10            ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_CTL_WAYS          ]              =   1;     //状态量
    extDevRatio.eAcParaRatio[IR_IT_x10            ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_IH_x10            ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_OT_x10            ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_OH_x10            ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_IT1_x10           ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_IT2_x10           ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_OT1_x10           ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_OT2_x10           ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_OT3_x10           ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_NET_AT_x10        ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_NET_AH_x10        ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_SYS_RUN_STS       ]              =   1;     //状态量
    extDevRatio.eAcParaRatio[IR_SYS_RUN_MOD       ]              =   1;     //状态量
    extDevRatio.eAcParaRatio[IR_EXSU_T_x10        ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_SUCT_T_x10        ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_EVAP_T_x10        ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_SUCT_P_x10        ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_EXSU_P_x10        ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_CMPR_PAHP_PC_x10  ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_SYSA_COND_T_x10   ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_SYSB_COND_T_x10   ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_SYSA_SUCT_SHT_x10 ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_SYSB_SUCT_SHT_x10 ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_ETH_I_x10         ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_ETH_HWL_V         ]              =   1;
    extDevRatio.eAcParaRatio[IR_IPWV_A_x10        ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_IPWV_B_x10        ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_IPWV_C_x10        ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_IPWF_A_x10        ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_IPWF_B_x10        ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_IPWF_C_x10        ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_SYS_TYPE          ]              =   1;
    extDevRatio.eAcParaRatio[IR_EFAN_AFV_x10      ]              =   1;
    extDevRatio.eAcParaRatio[IR_SYS_CCP           ]              =   1;
    extDevRatio.eAcParaRatio[IR_CMPR_F_x10        ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_CMPR_SET_F_x10    ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_INV_DC_VOLT_x10   ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_INV_OUT_VOLT_x10  ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_INV_OUT_CURR_x10  ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_INV_TEMP_x10      ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_INV_VER           ]              =   1;
    extDevRatio.eAcParaRatio[IR_EEVA_OPEN         ]              =   1;
    extDevRatio.eAcParaRatio[IR_EEVB_OPEN         ]              =   1;
    extDevRatio.eAcParaRatio[IR_CWVA_OPEN         ]              =   1;
    extDevRatio.eAcParaRatio[IR_CWVB_OPEN         ]              =   1;
    extDevRatio.eAcParaRatio[IR_SYS_WKTM          ]              =   1;
    extDevRatio.eAcParaRatio[IR_EFAN_WKTM         ]              =   1;
    extDevRatio.eAcParaRatio[IR_HUMI_WKTM         ]              =   1;
    extDevRatio.eAcParaRatio[IR_HRAT1_WKTM        ]              =   1;
    extDevRatio.eAcParaRatio[IR_HRAT2_WKTM        ]              =   1;
    extDevRatio.eAcParaRatio[IR_ODMA_WKTM         ]              =   1;
    extDevRatio.eAcParaRatio[IR_ODMB_WKTM         ]              =   1;
    extDevRatio.eAcParaRatio[IR_CMPRA_WKTM        ]              =   1;
    extDevRatio.eAcParaRatio[IR_CMPRB_WKTM        ]              =   1;
    extDevRatio.eAcParaRatio[IR_FLT_WKTM          ]              =   1;
    extDevRatio.eAcParaRatio[IR_TOTAL_KWH         ]              =   1;
    extDevRatio.eAcParaRatio[IR_SYS_CLCN          ]              =   1;
    extDevRatio.eAcParaRatio[IR_SYS_HTCN          ]              =   1;
    extDevRatio.eAcParaRatio[IR_SYS_IHCN          ]              =   1;
    extDevRatio.eAcParaRatio[IR_SYS_DHCN          ]              =   1;
    extDevRatio.eAcParaRatio[IR_EFAN_RS_x10       ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_SYS_LEWY_x10      ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_CMPRA_CTL_F       ]              =   1;
    extDevRatio.eAcParaRatio[IR_CMPRB_CTL_F       ]              =   1;
    extDevRatio.eAcParaRatio[IR_RT01              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RH01              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RT02              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RH02              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RT03              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RH03              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RT04              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RH04              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RT05              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RH05              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RT06              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RH06              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RT07              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RH07              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RT08              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RH08              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RT09              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RH09              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RT10              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RH10              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RT11              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RH11              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RT12              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RH12              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RT13              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RH13              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RT14              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RH14              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RT15              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RH15              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RT16              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_RH16              ]              = 0.1;
    extDevRatio.eAcParaRatio[IR_SFVER             ]              =   1;

    //单位

    extDevShow.eAcParaUnit[IR_T_x10             ]              = "℃";
    extDevShow.eAcParaUnit[IR_H_x10             ]              = "%";
    extDevShow.eAcParaUnit[IR_TS_x10            ]              = "℃";
    extDevShow.eAcParaUnit[IR_HS_x10            ]              = "%";
    extDevShow.eAcParaUnit[IR_CTL_WAYS          ]              = "";
    extDevShow.eAcParaUnit[IR_IT_x10            ]              = "℃";
    extDevShow.eAcParaUnit[IR_IH_x10            ]              = "%";
    extDevShow.eAcParaUnit[IR_OT_x10            ]              = "℃";
    extDevShow.eAcParaUnit[IR_OH_x10            ]              = "%";
    extDevShow.eAcParaUnit[IR_IT1_x10           ]              = "℃";
    extDevShow.eAcParaUnit[IR_IT2_x10           ]              = "℃";
    extDevShow.eAcParaUnit[IR_OT1_x10           ]              = "℃";
    extDevShow.eAcParaUnit[IR_OT2_x10           ]              = "℃";
    extDevShow.eAcParaUnit[IR_OT3_x10           ]              = "℃";
    extDevShow.eAcParaUnit[IR_NET_AT_x10        ]              = "℃";
    extDevShow.eAcParaUnit[IR_NET_AH_x10        ]              = "%";
    extDevShow.eAcParaUnit[IR_SYS_RUN_STS       ]              = "";
    extDevShow.eAcParaUnit[IR_SYS_RUN_MOD       ]              = "";
    extDevShow.eAcParaUnit[IR_EXSU_T_x10        ]              = "℃";
    extDevShow.eAcParaUnit[IR_SUCT_T_x10        ]              = "℃";
    extDevShow.eAcParaUnit[IR_EVAP_T_x10        ]              = "℃";
    extDevShow.eAcParaUnit[IR_SUCT_P_x10        ]              = "bar";
    extDevShow.eAcParaUnit[IR_EXSU_P_x10        ]              = "bar";
    extDevShow.eAcParaUnit[IR_CMPR_PAHP_PC_x10  ]              = "bar";
    extDevShow.eAcParaUnit[IR_SYSA_COND_T_x10   ]              = "℃";
    extDevShow.eAcParaUnit[IR_SYSB_COND_T_x10   ]              = "℃";
    extDevShow.eAcParaUnit[IR_SYSA_SUCT_SHT_x10 ]              = "℃";
    extDevShow.eAcParaUnit[IR_SYSB_SUCT_SHT_x10 ]              = "℃";
    extDevShow.eAcParaUnit[IR_ETH_I_x10         ]              = "A ";
    extDevShow.eAcParaUnit[IR_ETH_HWL_V         ]              = "V";
    extDevShow.eAcParaUnit[IR_IPWV_A_x10        ]              = "V";
    extDevShow.eAcParaUnit[IR_IPWV_B_x10        ]              = "V";
    extDevShow.eAcParaUnit[IR_IPWV_C_x10        ]              = "V";
    extDevShow.eAcParaUnit[IR_IPWF_A_x10        ]              = "Hz";
    extDevShow.eAcParaUnit[IR_IPWF_B_x10        ]              = "Hz";
    extDevShow.eAcParaUnit[IR_IPWF_C_x10        ]              = "Hz";
    extDevShow.eAcParaUnit[IR_SYS_TYPE          ]              = "";
    extDevShow.eAcParaUnit[IR_EFAN_AFV_x10      ]              = "";
    extDevShow.eAcParaUnit[IR_SYS_CCP           ]              = "";
    extDevShow.eAcParaUnit[IR_CMPR_F_x10        ]              = "Hz";
    extDevShow.eAcParaUnit[IR_CMPR_SET_F_x10    ]              = "Hz";
    extDevShow.eAcParaUnit[IR_INV_DC_VOLT_x10   ]              = "V";
    extDevShow.eAcParaUnit[IR_INV_OUT_VOLT_x10  ]              = "V";
    extDevShow.eAcParaUnit[IR_INV_OUT_CURR_x10  ]              = "A";
    extDevShow.eAcParaUnit[IR_INV_TEMP_x10      ]              = "℃";
    extDevShow.eAcParaUnit[IR_INV_VER           ]              = "";
    extDevShow.eAcParaUnit[IR_EEVA_OPEN         ]              = "";
    extDevShow.eAcParaUnit[IR_EEVB_OPEN         ]              = "";
    extDevShow.eAcParaUnit[IR_CWVA_OPEN         ]              = "";
    extDevShow.eAcParaUnit[IR_CWVB_OPEN         ]              = "";
    extDevShow.eAcParaUnit[IR_SYS_WKTM          ]              = "H";
    extDevShow.eAcParaUnit[IR_EFAN_WKTM         ]              = "H";
    extDevShow.eAcParaUnit[IR_HUMI_WKTM         ]              = "H";
    extDevShow.eAcParaUnit[IR_HRAT1_WKTM        ]              = "H";
    extDevShow.eAcParaUnit[IR_HRAT2_WKTM        ]              = "H";
    extDevShow.eAcParaUnit[IR_ODMA_WKTM         ]              = "H";
    extDevShow.eAcParaUnit[IR_ODMB_WKTM         ]              = "H";
    extDevShow.eAcParaUnit[IR_CMPRA_WKTM        ]              = "H";
    extDevShow.eAcParaUnit[IR_CMPRB_WKTM        ]              = "H";
    extDevShow.eAcParaUnit[IR_FLT_WKTM          ]              = "H";
    extDevShow.eAcParaUnit[IR_TOTAL_KWH         ]              = "kWh";
    extDevShow.eAcParaUnit[IR_SYS_CLCN          ]              = "";
    extDevShow.eAcParaUnit[IR_SYS_HTCN          ]              = "";
    extDevShow.eAcParaUnit[IR_SYS_IHCN          ]              = "";
    extDevShow.eAcParaUnit[IR_SYS_DHCN          ]              = "";
    extDevShow.eAcParaUnit[IR_EFAN_RS_x10       ]              = "%";
    extDevShow.eAcParaUnit[IR_SYS_LEWY_x10      ]              = "";
    extDevShow.eAcParaUnit[IR_CMPRA_CTL_F       ]              = "Hz";
    extDevShow.eAcParaUnit[IR_CMPRB_CTL_F       ]              = "Hz";
    extDevShow.eAcParaUnit[IR_RT01              ]              = "℃";
    extDevShow.eAcParaUnit[IR_RH01              ]              = "%";
    extDevShow.eAcParaUnit[IR_RT02              ]              = "℃";
    extDevShow.eAcParaUnit[IR_RH02              ]              = "%";
    extDevShow.eAcParaUnit[IR_RT03              ]              = "℃";
    extDevShow.eAcParaUnit[IR_RH03              ]              = "%";
    extDevShow.eAcParaUnit[IR_RT04              ]              = "℃";
    extDevShow.eAcParaUnit[IR_RH04              ]              = "%";
    extDevShow.eAcParaUnit[IR_RT05              ]              = "℃";
    extDevShow.eAcParaUnit[IR_RH05              ]              = "%";
    extDevShow.eAcParaUnit[IR_RT06              ]              = "℃";
    extDevShow.eAcParaUnit[IR_RH06              ]              = "%";
    extDevShow.eAcParaUnit[IR_RT07              ]              = "℃";
    extDevShow.eAcParaUnit[IR_RH07              ]              = "%";
    extDevShow.eAcParaUnit[IR_RT08              ]              = "℃";
    extDevShow.eAcParaUnit[IR_RH08              ]              = "%";
    extDevShow.eAcParaUnit[IR_RT09              ]              = "℃";
    extDevShow.eAcParaUnit[IR_RH09              ]              = "%";
    extDevShow.eAcParaUnit[IR_RT10              ]              = "℃";
    extDevShow.eAcParaUnit[IR_RH10              ]              = "%";
    extDevShow.eAcParaUnit[IR_RT11              ]              = "℃";
    extDevShow.eAcParaUnit[IR_RH11              ]              = "%";
    extDevShow.eAcParaUnit[IR_RT12              ]              = "℃";
    extDevShow.eAcParaUnit[IR_RH12              ]              = "%";
    extDevShow.eAcParaUnit[IR_RT13              ]              = "℃";
    extDevShow.eAcParaUnit[IR_RH13              ]              = "%";
    extDevShow.eAcParaUnit[IR_RT14              ]              = "℃";
    extDevShow.eAcParaUnit[IR_RH14              ]              = "%";
    extDevShow.eAcParaUnit[IR_RT15              ]              = "℃";
    extDevShow.eAcParaUnit[IR_RH15              ]              = "%";
    extDevShow.eAcParaUnit[IR_RT16              ]              = "℃";
    extDevShow.eAcParaUnit[IR_RH16              ]              = "%";
    extDevShow.eAcParaUnit[IR_SFVER             ]              = "";




    //UPS系数
    extDevRatio.eUpsRatio[eUpsParaBypVoltPhA]          = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaBypVoltPhB]          = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaBypVoltPhC]          = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaBypCurrPhA]          = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaBypCurrPhB]          = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaBypCurrPhC]          = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaBypFreqPhA]          = 0.01;
    extDevRatio.eUpsRatio[eUpsParaBypFreqPhB]          = 0.01;
    extDevRatio.eUpsRatio[eUpsParaBypFreqPhC]          = 0.01;
    extDevRatio.eUpsRatio[eUpsParaBypPfPhA]            = 0.01;
    extDevRatio.eUpsRatio[eUpsParaBypPfPhB]            = 0.01;
    extDevRatio.eUpsRatio[eUpsParaBypPfPhC]            = 0.01;
    extDevRatio.eUpsRatio[eUpsParaIpVoltPhA]           = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaIpVoltPhB]           = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaIpVoltPhC]           = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaIpCurrPhA]           = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaIpCurrPhB]           = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaIpCurrPhC]           = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaIpFreqPhA]           = 0.01;
    extDevRatio.eUpsRatio[eUpsParaIpFreqPhB]           = 0.01;
    extDevRatio.eUpsRatio[eUpsParaIpFreqPhC]           = 0.01;
    extDevRatio.eUpsRatio[eUpsParaIpPfPhA]             = 0.01;
    extDevRatio.eUpsRatio[eUpsParaIpPfPhB]             = 0.01;
    extDevRatio.eUpsRatio[eUpsParaIpPfPhC]             = 0.01;
    extDevRatio.eUpsRatio[eUpsParaOpVoltPhA]           = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaOpVoltPhB]           = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaOpVoltPhC]           = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaOpCurrPhA]           = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaOpCurrPhB]           = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaOpCurrPhC]           = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaOpFreqPhA]           = 0.01;
    extDevRatio.eUpsRatio[eUpsParaOpFreqPhB]           = 0.01;
    extDevRatio.eUpsRatio[eUpsParaOpFreqPhC]           = 0.01;
    extDevRatio.eUpsRatio[eUpsParaOpPfPhA]             = 0.01;
    extDevRatio.eUpsRatio[eUpsParaOpPfPhB]             = 0.01;
    extDevRatio.eUpsRatio[eUpsParaOpPfPhC]             = 0.01;
    extDevRatio.eUpsRatio[eUpsParaOpKvaPhA]            = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaOpKvaPhB]            = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaOpKvaPhC]            = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaOpKwPhA]             = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaOpKwPhB]             = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaOpKwPhC]             = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaLdPerPhA]            = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaLdPerPhB]            = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaLdPerPhC]            = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaEnvirTemp]           = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaBattVoltPos]         = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaBattVoltNeg]         = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaBattCurrPos]         = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaBattCurrNeg]         = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaBattTemp]            = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaBattRemdTime]        = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaBattCapa]            = 0.1 ;
    extDevRatio.eUpsRatio[eUpsParaBypFanRunTime]       = 1   ;

    //电量仪系数
    extDevRatio.eMeterRatio[eMeterParaCurrA     ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaCurrB     ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaCurrC     ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaCurrN     ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaMaxCurrA  ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaMaxCurrB  ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaMaxCurrC  ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaMaxCurrN  ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaVoltAB    ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaVoltBC    ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaVoltCA    ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaVoltA     ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaVoltB     ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaVoltC     ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaFreq      ]       = 0.01;
    extDevRatio.eMeterRatio[eMeterParaKwAll     ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaMaxKwAll  ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaKwA       ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaKwB       ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaKwC       ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaKVarAll   ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaMaxKVarAll]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaKVarA     ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaKVarB     ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaKVarC     ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaKVAAll    ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaMaxKVAAll ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaKvaA      ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaKvaB      ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaKvaC      ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaPfAll     ]       = 0.01;
    extDevRatio.eMeterRatio[eMeterParaPfA       ]       = 0.01;
    extDevRatio.eMeterRatio[eMeterParaPfB       ]       = 0.01;
    extDevRatio.eMeterRatio[eMeterParaPfC       ]       = 0.01;
    extDevRatio.eMeterRatio[eMeterParaKWH_High  ]       = 1;
    extDevRatio.eMeterRatio[eMeterParaKWH_Low   ]       = 1;
    extDevRatio.eMeterRatio[eMeterParaKVarH_High]       = 1;
    extDevRatio.eMeterRatio[eMeterParaKVarH_Low ]       = 1;
    extDevRatio.eMeterRatio[eMeterParaVoltABThd ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaVoltBCThd ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaVoltCAThd ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaVoltAThd  ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaVoltBThd  ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaVoltCThd  ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaCurrAThd  ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaCurrBThd  ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaCurrCThd  ]       = 0.1;
    extDevRatio.eMeterRatio[eMeterParaCurrNThd  ]       = 0.1;

    //初始化电量仪 默认为uint16
    for(int i=0;i<eMeterParaNum;i++){
        extDevRatio.eMeterIsInt16[i] = false;
    }

    extDevRatio.eMeterIsInt16[eMeterParaKwAll     ] = true;
    extDevRatio.eMeterIsInt16[eMeterParaMaxKwAll  ] = true;
    extDevRatio.eMeterIsInt16[eMeterParaKwA       ] = true;
    extDevRatio.eMeterIsInt16[eMeterParaKwB       ] = true;
    extDevRatio.eMeterIsInt16[eMeterParaKwC       ] = true;
    extDevRatio.eMeterIsInt16[eMeterParaKVarAll   ] = true;
    extDevRatio.eMeterIsInt16[eMeterParaMaxKVarAll] = true;
    extDevRatio.eMeterIsInt16[eMeterParaKVarA     ] = true;
    extDevRatio.eMeterIsInt16[eMeterParaKVarB     ] = true;
    extDevRatio.eMeterIsInt16[eMeterParaKVarC     ] = true;
    extDevRatio.eMeterIsInt16[eMeterParaPfAll     ] = true;
    extDevRatio.eMeterIsInt16[eMeterParaPfA       ] = true;
    extDevRatio.eMeterIsInt16[eMeterParaPfB       ] = true;
    extDevRatio.eMeterIsInt16[eMeterParaPfC       ] = true;

    //水浸系数
    extDevRatio.eLeakRatio[eLeakParaLeakPos    ]        = 0.1;
    extDevRatio.eLeakRatio[eLeakParaAlmSts     ]        = 1  ;
    extDevRatio.eLeakRatio[eLeakParaCableLength]        = 0.1;
    extDevRatio.eLeakRatio[eLeakParaCableResist]        = 1  ;
    extDevRatio.eLeakRatio[eLeakParaOutIO      ]        = 1  ;
    extDevRatio.eLeakRatio[eLeakParaAlmLevel   ]        = 1  ;

    //spds系数 main
    extDevRatio.eSpdsMainRatio[eSpdsMainVolt_AB  ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainVolt_BC  ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainVolt_CA  ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainVolt_LN  ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainVolt_A   ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainVolt_B   ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainVolt_C   ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainCurr_A   ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainCurr_B   ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainCurr_C   ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainCurr_N   ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainLoad_A   ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainLoad_B   ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainLoad_C   ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainFreq_A   ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainFreq_B   ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainFreq_C   ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainKWhHi_A  ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainKWhLo_A  ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainKWhHi_B  ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainKWhLo_B  ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainKWhHi_C  ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainKWhLo_C  ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainKva_A    ]        = 0.01;
    extDevRatio.eSpdsMainRatio[eSpdsMainKva_B    ]        = 0.01;
    extDevRatio.eSpdsMainRatio[eSpdsMainKva_C    ]        = 0.01;
    extDevRatio.eSpdsMainRatio[eSpdsMainKw_A     ]        = 0.01;
    extDevRatio.eSpdsMainRatio[eSpdsMainKw_B     ]        = 0.01;
    extDevRatio.eSpdsMainRatio[eSpdsMainKw_C     ]        = 0.01;
    extDevRatio.eSpdsMainRatio[eSpdsMainKVar_A   ]        = 0.01;
    extDevRatio.eSpdsMainRatio[eSpdsMainKVar_B   ]        = 0.01;
    extDevRatio.eSpdsMainRatio[eSpdsMainKVar_C   ]        = 0.01;
    extDevRatio.eSpdsMainRatio[eSpdsMainPF_A     ]        = 0.01;
    extDevRatio.eSpdsMainRatio[eSpdsMainPF_B     ]        = 0.01;
    extDevRatio.eSpdsMainRatio[eSpdsMainPF_C     ]        = 0.01;
    extDevRatio.eSpdsMainRatio[eSpdsMainTHDU_A   ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainTHDU_B   ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainTHDU_C   ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainTHDI_A   ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainTHDI_B   ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainTHDI_C   ]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainKWhHi_all]        = 0.1 ;
    extDevRatio.eSpdsMainRatio[eSpdsMainKWhLo_all]        = 0.1 ;

    //spds系数 Branch
    extDevRatio.eSpdsBranchRatio[eSpdsBranchVolt       ]          = 0.1 ;
    extDevRatio.eSpdsBranchRatio[eSpdsBranchCurr       ]          = 0.1 ;
    extDevRatio.eSpdsBranchRatio[eSpdsBranchLoad       ]          = 0.1 ;
    extDevRatio.eSpdsBranchRatio[eSpdsBranchKWhHi      ]          = 0.01;
    extDevRatio.eSpdsBranchRatio[eSpdsBranchKWhLo      ]          = 0.01;
    extDevRatio.eSpdsBranchRatio[eSpdsBranchKva        ]          = 0.01;
    extDevRatio.eSpdsBranchRatio[eSpdsBranchKw         ]          = 0.01;
    extDevRatio.eSpdsBranchRatio[eSpdsBranchTHDI       ]          = 0.1 ;
    extDevRatio.eSpdsBranchRatio[eSpdsBranchSwSts      ]          = 1;
    extDevRatio.eSpdsBranchRatio[eSpdsBranchCurrOvUp   ]          = 1;
    extDevRatio.eSpdsBranchRatio[eSpdsBranchCurrUnderLo]          = 1;

    //bms系数

    extDevRatio.eBMSGroupRatio[eBmsGroupAlm          ]    =   1;
    extDevRatio.eBMSGroupRatio[eBmsGroupVoltOvH      ]    =   1;
    extDevRatio.eBMSGroupRatio[eBmsGroupVoltOvL      ]    =   1;
    extDevRatio.eBMSGroupRatio[eBmsGroupChgCurrAlm   ]    =   1;
    extDevRatio.eBMSGroupRatio[eBmsGroupDisChgCurrAlm]    =   1;
    extDevRatio.eBMSGroupRatio[eBmsGroupBattSwOpenAlm]    =   1;
    extDevRatio.eBMSGroupRatio[eBmsGroupCommFailAlm  ]    =   1;
    extDevRatio.eBMSGroupRatio[eBmsGroupSocLowAlm    ]    =   1;
    extDevRatio.eBMSGroupRatio[eBmsGroupBattSts      ]    =   1;
    extDevRatio.eBMSGroupRatio[eBmsGroupBattNum      ]    =   1;
    extDevRatio.eBMSGroupRatio[eBmsGroupBattType     ]    =   1;
    extDevRatio.eBMSGroupRatio[eBmsGroupBattAH       ]    =   1;
    extDevRatio.eBMSGroupRatio[eBmsGroupVolt         ]    =   0.1  ;
    extDevRatio.eBMSGroupRatio[eBmsGroupCurr         ]    =   0.1  ;
    extDevRatio.eBMSGroupRatio[eBmsGroupAvgCellVolt  ]    =   0.001;
    extDevRatio.eBMSGroupRatio[eBmsGroupMaxCellVolt  ]    =   0.001;
    extDevRatio.eBMSGroupRatio[eBmsGroupMaxCellVoltID]    =   1    ;
    extDevRatio.eBMSGroupRatio[eBmsGroupMinCellVolt  ]    =   0.001;
    extDevRatio.eBMSGroupRatio[eBmsGroupMinCellVoltID]    =   1    ;
    extDevRatio.eBMSGroupRatio[eBmsGroupAvgCellRes   ]    =   0.001;
    extDevRatio.eBMSGroupRatio[eBmsGroupMaxCellRes   ]    =   0.001;
    extDevRatio.eBMSGroupRatio[eBmsGroupMaxCellResID ]    =   1    ;
    extDevRatio.eBMSGroupRatio[eBmsGroupMinCellRes   ]    =   0.001;
    extDevRatio.eBMSGroupRatio[eBmsGroupMinCellResID ]    =   1    ;
    extDevRatio.eBMSGroupRatio[eBmsGroupAvgCellTemp  ]    =   0.1  ;
    extDevRatio.eBMSGroupRatio[eBmsGroupMaxCellTemp  ]    =   0.1  ;
    extDevRatio.eBMSGroupRatio[eBmsGroupMaxCellTempID]    =   1    ;
    extDevRatio.eBMSGroupRatio[eBmsGroupMinCellTemp  ]    =   0.1  ;
    extDevRatio.eBMSGroupRatio[eBmsGroupMinCellTempID]    =   1    ;
    extDevRatio.eBMSGroupRatio[eBmsGroupBattSOC      ]    =   0.1  ;
    extDevRatio.eBMSGroupRatio[eBmsGroupBattSOH      ]    =   0.1  ;
    extDevRatio.eBMSGroupRatio[eBmsGroupBalanceID1   ]    =   1;
    extDevRatio.eBMSGroupRatio[eBmsGroupBalanceID2   ]    =   1;

    //
    extDevRatio.eBMSCellRatio[eBmsCellVolt           ] =   1;   //?
    extDevRatio.eBMSCellRatio[eBmsCellTemp           ] =   1;   //?
    extDevRatio.eBMSCellRatio[eBmsCellRes            ] =   1;   //?
    extDevRatio.eBMSCellRatio[eBmsCellVoltOvHvAlm    ] =   1;
    extDevRatio.eBMSCellRatio[eBmsCellVoltOvLAlm     ] =   1;
    extDevRatio.eBMSCellRatio[eBmsCellResOvHAlm      ] =   1;
    extDevRatio.eBMSCellRatio[eBmsCellTempOvHAlm     ] =   1;
    extDevRatio.eBMSCellRatio[eBmsCellResDiffOvHAlm  ] =   1;
    extDevRatio.eBMSCellRatio[eBmsCellVBUSCommFailAlm] =   1;
    extDevRatio.eBMSCellRatio[eBmsCellVoltAnomalyAlm ] =   1;
    extDevRatio.eBMSCellRatio[eBmsCellTempAnomalyAlm ] =   1;

    //bms单位

    extDevRatio.eBMSGroupUnit[eBmsGroupAlm          ]    =   "";
    extDevRatio.eBMSGroupUnit[eBmsGroupVoltOvH      ]    =   "";
    extDevRatio.eBMSGroupUnit[eBmsGroupVoltOvL      ]    =   "";
    extDevRatio.eBMSGroupUnit[eBmsGroupChgCurrAlm   ]    =   "";
    extDevRatio.eBMSGroupUnit[eBmsGroupDisChgCurrAlm]    =   "";
    extDevRatio.eBMSGroupUnit[eBmsGroupBattSwOpenAlm]    =   "";
    extDevRatio.eBMSGroupUnit[eBmsGroupCommFailAlm  ]    =   "";
    extDevRatio.eBMSGroupUnit[eBmsGroupSocLowAlm    ]    =   "";
    extDevRatio.eBMSGroupUnit[eBmsGroupBattSts      ]    =   "";
    extDevRatio.eBMSGroupUnit[eBmsGroupBattNum      ]    =   "";
    extDevRatio.eBMSGroupUnit[eBmsGroupBattType     ]    =   "";
    extDevRatio.eBMSGroupUnit[eBmsGroupBattAH       ]    =   "";
    extDevRatio.eBMSGroupUnit[eBmsGroupVolt         ]    =   "V";
    extDevRatio.eBMSGroupUnit[eBmsGroupCurr         ]    =   "A";
    extDevRatio.eBMSGroupUnit[eBmsGroupAvgCellVolt  ]    =   "V";
    extDevRatio.eBMSGroupUnit[eBmsGroupMaxCellVolt  ]    =   "V";
    extDevRatio.eBMSGroupUnit[eBmsGroupMaxCellVoltID]    =   "";
    extDevRatio.eBMSGroupUnit[eBmsGroupMinCellVolt  ]    =   "V";
    extDevRatio.eBMSGroupUnit[eBmsGroupMinCellVoltID]    =   "";
    extDevRatio.eBMSGroupUnit[eBmsGroupAvgCellRes   ]    =   "mΩ";
    extDevRatio.eBMSGroupUnit[eBmsGroupMaxCellRes   ]    =   "mΩ";
    extDevRatio.eBMSGroupUnit[eBmsGroupMaxCellResID ]    =   "";
    extDevRatio.eBMSGroupUnit[eBmsGroupMinCellRes   ]    =   "mΩ";
    extDevRatio.eBMSGroupUnit[eBmsGroupMinCellResID ]    =   "";
    extDevRatio.eBMSGroupUnit[eBmsGroupAvgCellTemp  ]    =   "℃";
    extDevRatio.eBMSGroupUnit[eBmsGroupMaxCellTemp  ]    =   "℃";
    extDevRatio.eBMSGroupUnit[eBmsGroupMaxCellTempID]    =   "";
    extDevRatio.eBMSGroupUnit[eBmsGroupMinCellTemp  ]    =   "℃";
    extDevRatio.eBMSGroupUnit[eBmsGroupMinCellTempID]    =   "";
    extDevRatio.eBMSGroupUnit[eBmsGroupBattSOC      ]    =   "%";
    extDevRatio.eBMSGroupUnit[eBmsGroupBattSOH      ]    =   "%";
    extDevRatio.eBMSGroupUnit[eBmsGroupBalanceID1   ]    =   "";
    extDevRatio.eBMSGroupUnit[eBmsGroupBalanceID2   ]    =   "";

    //
    extDevRatio.eBMSCellUnit[eBmsCellVolt           ] =   "V";
    extDevRatio.eBMSCellUnit[eBmsCellTemp           ] =   "℃";
    extDevRatio.eBMSCellUnit[eBmsCellRes            ] =   "mΩ";
    extDevRatio.eBMSCellUnit[eBmsCellVoltOvHvAlm    ] =   "";
    extDevRatio.eBMSCellUnit[eBmsCellVoltOvLAlm     ] =   "";
    extDevRatio.eBMSCellUnit[eBmsCellResOvHAlm      ] =   "";
    extDevRatio.eBMSCellUnit[eBmsCellTempOvHAlm     ] =   "";
    extDevRatio.eBMSCellUnit[eBmsCellResDiffOvHAlm  ] =   "";
    extDevRatio.eBMSCellUnit[eBmsCellVBUSCommFailAlm] =   "";
    extDevRatio.eBMSCellUnit[eBmsCellVoltAnomalyAlm ] =   "";
    extDevRatio.eBMSCellUnit[eBmsCellTempAnomalyAlm ] =   "";





}



void ExtDevShowInit()
{


    //--------空调-------------------------------------------------------------------



    //-----------------------------------------------------------------------

    //UPS-----------------------------
    //状态
    for(int i=0;i<eUpsStsNum;i++){
        extDevShow.eUpsStsShow[i][0] = langN.show[langEnum::strNorm]; //"正常";
        extDevShow.eUpsStsShow[i][1] = langN.show[langEnum::strAlm]; //"告警";
        extDevShow.eUpsStsShow[i][2] = langN.show[langEnum::strInvalid]; //"无效";
        extDevShow.eUpsStsShow[i][3] = langN.show[langEnum::strInvalid]; //"无效";
        extDevShow.eUpsStsShow[i][4] = langN.show[langEnum::strInvalid]; //"无效";
        extDevShow.eUpsStsShow[i][5] = langN.show[langEnum::strInvalid]; //"无效";
    }
    extDevShow.eUpsStsShow[eUpsStsGeneralAlm][0]              = "";
    extDevShow.eUpsStsShow[eUpsStsGeneralAlm][1]              = langN.show[langEnum::strNorm]; //"正常";
    extDevShow.eUpsStsShow[eUpsStsGeneralAlm][2]              = langN.show[langEnum::strAlm]; //"告警";
    extDevShow.eUpsStsShow[eUpsStsLoadOnSrc][0]              = langN.show[langEnum::strNoSupp];  //"均不供电";
    extDevShow.eUpsStsShow[eUpsStsLoadOnSrc][1]              = langN.show[langEnum::strUpsSupp]; //"ups供电";
    extDevShow.eUpsStsShow[eUpsStsLoadOnSrc][2]              = langN.show[langEnum::strBypSupp]; //"旁路供电";
    extDevShow.eUpsStsShow[eUpsStsBypOvLd][0]              = langN.show[langEnum::strNorm]; //"正常";          // 0: noraml, 1: OvLdTout; 2: OvLd
    extDevShow.eUpsStsShow[eUpsStsBypOvLd][1]              = langN.show[langEnum::strOvLoadTO]; //"过载超时";
    extDevShow.eUpsStsShow[eUpsStsBypOvLd][2]              = langN.show[langEnum::strOvLoad]; //"过载";
    extDevShow.eUpsStsShow[eUpsStsInvOvLd][0]              = langN.show[langEnum::strNorm]; //"正常";
    extDevShow.eUpsStsShow[eUpsStsInvOvLd][1]              = langN.show[langEnum::strOvLoadTO]; //"过载超时";
    extDevShow.eUpsStsShow[eUpsStsInvOvLd][2]              = langN.show[langEnum::strOvLoad]; //"过载";
    extDevShow.eUpsStsShow[eUpsStsBattSts][0]              = langN.show[langEnum::strDisconn]; //"未连接";
    extDevShow.eUpsStsShow[eUpsStsBattSts][1]              = langN.show[langEnum::strBattNotWork]; //"电池未工作";
    extDevShow.eUpsStsShow[eUpsStsBattSts][2]              = langN.show[langEnum::strBattFloat];  //"电池浮充";
    extDevShow.eUpsStsShow[eUpsStsBattSts][3]              = langN.show[langEnum::strBattBoost];  //"电池均充";
    extDevShow.eUpsStsShow[eUpsStsBattSts][4]              = langN.show[langEnum::strBattDisChar];  //"电池放电";

    extDevShow.eUpsStsShow[eUpsStsBattSts][5]              = langN.show[langEnum::strHide]+" "+langN.show[langEnum::strBattSts]; //"隐藏电池状态";
    extDevShow.eUpsStsShow[eUpsStsBattTestResult][0]              = langN.show[langEnum::strNoTest]; //"未自检";
    extDevShow.eUpsStsShow[eUpsStsBattTestResult][1]              = langN.show[langEnum::strSuc]; //"成功";
    extDevShow.eUpsStsShow[eUpsStsBattTestResult][2]              = langN.show[langEnum::strFail]; //"失败";
    extDevShow.eUpsStsShow[eUpsStsBattTestResult][3]              = langN.show[langEnum::strTesting]; //"自检中";
    extDevShow.eUpsStsShow[eUpsStsBattMaintResult][0]              = langN.show[langEnum::strUnMaintTest]; //"未维护测试";
    extDevShow.eUpsStsShow[eUpsStsBattMaintResult][1]              = langN.show[langEnum::strSuc]; //"成功";
    extDevShow.eUpsStsShow[eUpsStsBattMaintResult][2]              = langN.show[langEnum::strFail]; //"失败";
    extDevShow.eUpsStsShow[eUpsStsBattMaintResult][3]              = langN.show[langEnum::strMaintTesting]; //"维护测试中";
    extDevShow.eUpsStsShow[eUpsStsOnUpsInhibited][0]              =  langN.show[langEnum::strEnable];//"可用";
    extDevShow.eUpsStsShow[eUpsStsOnUpsInhibited][1]              = langN.show[langEnum::strDisable]; //"不可用";
    extDevShow.eUpsStsShow[eUpsStsManualTxByp][0]              = langN.show[langEnum::strMains]; //"主路输入";
    extDevShow.eUpsStsShow[eUpsStsManualTxByp][1]              = langN.show[langEnum::strByp]; //"旁路";
    extDevShow.eUpsStsShow[eUpsStsRecSts][0]              = langN.show[langEnum::strClose]; //"关闭";
    extDevShow.eUpsStsShow[eUpsStsRecSts][1]              =  langN.show[langEnum::strSoftStart];//"软启动";
    extDevShow.eUpsStsShow[eUpsStsRecSts][2]              = langN.show[langEnum::strNorm]; //"正常工作";

    //参数单位
    extDevShow.eUpsParaUnit[eUpsParaBypVoltPhA]         = "V";
    extDevShow.eUpsParaUnit[eUpsParaBypVoltPhB]         = "V";
    extDevShow.eUpsParaUnit[eUpsParaBypVoltPhC]         = "V";
    extDevShow.eUpsParaUnit[eUpsParaBypCurrPhA]         = "A";
    extDevShow.eUpsParaUnit[eUpsParaBypCurrPhB]         = "A";
    extDevShow.eUpsParaUnit[eUpsParaBypCurrPhC]         = "A";
    extDevShow.eUpsParaUnit[eUpsParaBypFreqPhA]         = "Hz";
    extDevShow.eUpsParaUnit[eUpsParaBypFreqPhB]         = "Hz";
    extDevShow.eUpsParaUnit[eUpsParaBypFreqPhC]         = "Hz";
    extDevShow.eUpsParaUnit[eUpsParaBypPfPhA]           = "";
    extDevShow.eUpsParaUnit[eUpsParaBypPfPhB]           = "";
    extDevShow.eUpsParaUnit[eUpsParaBypPfPhC]           = "";
    extDevShow.eUpsParaUnit[eUpsParaIpVoltPhA]          = "V";
    extDevShow.eUpsParaUnit[eUpsParaIpVoltPhB]          = "V";
    extDevShow.eUpsParaUnit[eUpsParaIpVoltPhC]          = "V";
    extDevShow.eUpsParaUnit[eUpsParaIpCurrPhA]          = "A";
    extDevShow.eUpsParaUnit[eUpsParaIpCurrPhB]          = "A";
    extDevShow.eUpsParaUnit[eUpsParaIpCurrPhC]          = "A";
    extDevShow.eUpsParaUnit[eUpsParaIpFreqPhA]          = "Hz";
    extDevShow.eUpsParaUnit[eUpsParaIpFreqPhB]          = "Hz";
    extDevShow.eUpsParaUnit[eUpsParaIpFreqPhC]          = "Hz";
    extDevShow.eUpsParaUnit[eUpsParaIpPfPhA]            = "";
    extDevShow.eUpsParaUnit[eUpsParaIpPfPhB]            = "";
    extDevShow.eUpsParaUnit[eUpsParaIpPfPhC]            = "";
    extDevShow.eUpsParaUnit[eUpsParaOpVoltPhA]          = "V";
    extDevShow.eUpsParaUnit[eUpsParaOpVoltPhB]          = "V";
    extDevShow.eUpsParaUnit[eUpsParaOpVoltPhC]          = "V";
    extDevShow.eUpsParaUnit[eUpsParaOpCurrPhA]          = "A";
    extDevShow.eUpsParaUnit[eUpsParaOpCurrPhB]          = "A";
    extDevShow.eUpsParaUnit[eUpsParaOpCurrPhC]          = "A";
    extDevShow.eUpsParaUnit[eUpsParaOpFreqPhA]          = "Hz";
    extDevShow.eUpsParaUnit[eUpsParaOpFreqPhB]          = "Hz";
    extDevShow.eUpsParaUnit[eUpsParaOpFreqPhC]          = "Hz";
    extDevShow.eUpsParaUnit[eUpsParaOpPfPhA]            = "";
    extDevShow.eUpsParaUnit[eUpsParaOpPfPhB]            = "";
    extDevShow.eUpsParaUnit[eUpsParaOpPfPhC]            = "";
    extDevShow.eUpsParaUnit[eUpsParaOpKvaPhA]           = "kVA";
    extDevShow.eUpsParaUnit[eUpsParaOpKvaPhB]           = "kVA";
    extDevShow.eUpsParaUnit[eUpsParaOpKvaPhC]           = "kVA";
    extDevShow.eUpsParaUnit[eUpsParaOpKwPhA]            = "kW";
    extDevShow.eUpsParaUnit[eUpsParaOpKwPhB]            = "kW";
    extDevShow.eUpsParaUnit[eUpsParaOpKwPhC]            = "kW";
    extDevShow.eUpsParaUnit[eUpsParaLdPerPhA]           = "%";
    extDevShow.eUpsParaUnit[eUpsParaLdPerPhB]           = "%";
    extDevShow.eUpsParaUnit[eUpsParaLdPerPhC]           = "%";
    extDevShow.eUpsParaUnit[eUpsParaEnvirTemp]          = "℃";
    extDevShow.eUpsParaUnit[eUpsParaBattVoltPos]        = "V";
    extDevShow.eUpsParaUnit[eUpsParaBattVoltNeg]        = "V";
    extDevShow.eUpsParaUnit[eUpsParaBattCurrPos]        = "A";
    extDevShow.eUpsParaUnit[eUpsParaBattCurrNeg]        = "A";
    extDevShow.eUpsParaUnit[eUpsParaBattTemp]           = "℃";
    extDevShow.eUpsParaUnit[eUpsParaBattRemdTime]       = langN.show[langEnum::strMinute];     //"分钟";
    extDevShow.eUpsParaUnit[eUpsParaBattCapa]           = "%";
    extDevShow.eUpsParaUnit[eUpsParaBypFanRunTime]      = langN.show[langEnum::strHour];    //"小时";

    //UPS cfg状态
    extDevShow.eUpsCfgShow[eUpsCfgSysMode] [1]          = "single";
    extDevShow.eUpsCfgShow[eUpsCfgSysMode] [2]          = "parallel";
    extDevShow.eUpsCfgShow[eUpsCfgSysMode] [4]          = "single ECO";
    extDevShow.eUpsCfgShow[eUpsCfgSysMode] [6]          = "parallel ECO";
    extDevShow.eUpsCfgShow[eUpsCfgSysMode] [8]          = "LBS";
    extDevShow.eUpsCfgShow[eUpsCfgSysMode] [10]         = "parallel LBS";


    //UPS cfg单位
    extDevShow.eUpsCfgUnit[eUpsCfgBattNum ]             = "";
    extDevShow.eUpsCfgUnit[eUpsCfgBattAH  ]             = "AH";
    extDevShow.eUpsCfgUnit[eUpsCfgCabPower]             = "kVA";
    extDevShow.eUpsCfgUnit[eUpsCfgIpVolt  ]             = "V";
    extDevShow.eUpsCfgUnit[eUpsCfgIpHz    ]             = "Hz";
    extDevShow.eUpsCfgUnit[eUpsCfgOpVolt  ]             = "V";
    extDevShow.eUpsCfgUnit[eUpsCfgOpHz    ]             = "Hz";



    //电量仪单位
    extDevShow.eMeterParaUnit[eMeterParaCurrA     ]     = "A";
    extDevShow.eMeterParaUnit[eMeterParaCurrB     ]     = "A";
    extDevShow.eMeterParaUnit[eMeterParaCurrC     ]     = "A";
    extDevShow.eMeterParaUnit[eMeterParaCurrN     ]     = "A";
    extDevShow.eMeterParaUnit[eMeterParaMaxCurrA  ]     = "A";
    extDevShow.eMeterParaUnit[eMeterParaMaxCurrB  ]     = "A";
    extDevShow.eMeterParaUnit[eMeterParaMaxCurrC  ]     = "A";
    extDevShow.eMeterParaUnit[eMeterParaMaxCurrN  ]     = "A";
    extDevShow.eMeterParaUnit[eMeterParaVoltAB    ]     = "V";
    extDevShow.eMeterParaUnit[eMeterParaVoltBC    ]     = "V";
    extDevShow.eMeterParaUnit[eMeterParaVoltCA    ]     = "V";
    extDevShow.eMeterParaUnit[eMeterParaVoltA     ]     = "V";
    extDevShow.eMeterParaUnit[eMeterParaVoltB     ]     = "V";
    extDevShow.eMeterParaUnit[eMeterParaVoltC     ]     = "V";
    extDevShow.eMeterParaUnit[eMeterParaFreq      ]     = "Hz";
    extDevShow.eMeterParaUnit[eMeterParaKwAll     ]     = "kW";
    extDevShow.eMeterParaUnit[eMeterParaMaxKwAll  ]     = "kW";
    extDevShow.eMeterParaUnit[eMeterParaKwA       ]     = "kW";
    extDevShow.eMeterParaUnit[eMeterParaKwB       ]     = "kW";
    extDevShow.eMeterParaUnit[eMeterParaKwC       ]     = "kW";
    extDevShow.eMeterParaUnit[eMeterParaKVarAll   ]     = "kVar";
    extDevShow.eMeterParaUnit[eMeterParaMaxKVarAll]     = "kVar";
    extDevShow.eMeterParaUnit[eMeterParaKVarA     ]     = "kVar";
    extDevShow.eMeterParaUnit[eMeterParaKVarB     ]     = "kVar";
    extDevShow.eMeterParaUnit[eMeterParaKVarC     ]     = "kVar";
    extDevShow.eMeterParaUnit[eMeterParaKVAAll    ]     = "kVA";
    extDevShow.eMeterParaUnit[eMeterParaMaxKVAAll ]     = "kVA";
    extDevShow.eMeterParaUnit[eMeterParaKvaA      ]     = "kVA";
    extDevShow.eMeterParaUnit[eMeterParaKvaB      ]     = "kVA";
    extDevShow.eMeterParaUnit[eMeterParaKvaC      ]     = "kVA";
    extDevShow.eMeterParaUnit[eMeterParaPfAll     ]     = "";
    extDevShow.eMeterParaUnit[eMeterParaPfA       ]     = "";
    extDevShow.eMeterParaUnit[eMeterParaPfB       ]     = "";
    extDevShow.eMeterParaUnit[eMeterParaPfC       ]     = "";
    extDevShow.eMeterParaUnit[eMeterParaKWH_High  ]     = "kW·h";
    extDevShow.eMeterParaUnit[eMeterParaKWH_Low   ]     = "kW·h";
    extDevShow.eMeterParaUnit[eMeterParaKVarH_High]     = "kVar·h";
    extDevShow.eMeterParaUnit[eMeterParaKVarH_Low ]     = "kVar·h";
    extDevShow.eMeterParaUnit[eMeterParaVoltABThd ]     = "%";
    extDevShow.eMeterParaUnit[eMeterParaVoltBCThd ]     = "%";
    extDevShow.eMeterParaUnit[eMeterParaVoltCAThd ]     = "%";
    extDevShow.eMeterParaUnit[eMeterParaVoltAThd  ]     = "%";
    extDevShow.eMeterParaUnit[eMeterParaVoltBThd  ]     = "%";
    extDevShow.eMeterParaUnit[eMeterParaVoltCThd  ]     = "%";
    extDevShow.eMeterParaUnit[eMeterParaCurrAThd  ]     = "%";
    extDevShow.eMeterParaUnit[eMeterParaCurrBThd  ]     = "%";
    extDevShow.eMeterParaUnit[eMeterParaCurrCThd  ]     = "%";
    extDevShow.eMeterParaUnit[eMeterParaCurrNThd  ]     = "%";

    //温湿度
    extDevShow.eThsParaShow[eThsParaAlmSts][0]          = langN.show[langEnum::strIntAlm]; //"综合告警";
    extDevShow.eThsParaShow[eThsParaAlmSts][1]          = langN.show[langEnum::strHighTempAlm]; //"高温告警";
    extDevShow.eThsParaShow[eThsParaAlmSts][2]          = langN.show[langEnum::strLowTempAlm]; //"低温告警";
    extDevShow.eThsParaShow[eThsParaAlmSts][3]          = langN.show[langEnum::strHighHumAlm]; //"高湿告警";
    extDevShow.eThsParaShow[eThsParaAlmSts][4]          = langN.show[langEnum::strLowHumAlm]; //"低湿告警";
    extDevShow.eThsParaShow[eThsParaAlmSts][5]          = langN.show[langEnum::strNorm]; //"无告警";
    //温湿度单位
    extDevShow.eThsParaUnit[eThsParaTmp]                = "℃";
    extDevShow.eThsParaUnit[eThsParaHum]                = "%";
    extDevShow.eThsParaUnit[eThsParaTmpUpper  ]         = "℃";
    extDevShow.eThsParaUnit[eThsParaTmpLower  ]         = "℃";
    extDevShow.eThsParaUnit[eThsParaTmpAlmDiff]         = "℃";
    extDevShow.eThsParaUnit[eThsParaHumUpper  ]         = "%";
    extDevShow.eThsParaUnit[eThsParaHumLower  ]         = "%";
    extDevShow.eThsParaUnit[eThsParaHumAlmDiff]         = "%";


    //水浸
    extDevShow.eLeakParaShow[eLeakParaAlmSts][0]         = langN.show[langEnum::strNorm]; //"正常";
    extDevShow.eLeakParaShow[eLeakParaAlmSts][1]         = langN.show[langEnum::strLeakage]; //"漏水";
    extDevShow.eLeakParaShow[eLeakParaAlmSts][2]         = langN.show[langEnum::strCabOpen];    //"线缆断路";
    extDevShow.eLeakParaShow[eLeakParaAlmSts][3]         = langN.show[langEnum::strCabInter];     //"线缆干扰";
    extDevShow.eLeakParaShow[eLeakParaAlmSts][4]         = langN.show[langEnum::strCabLong];     //"线缆太长";
    extDevShow.eLeakParaShow[eLeakParaAlmLevel][0]       = "level1";
    extDevShow.eLeakParaShow[eLeakParaAlmLevel][1]       = "level2";
    extDevShow.eLeakParaShow[eLeakParaAlmLevel][2]       = "level3";
    extDevShow.eLeakParaShow[eLeakParaAlmLevel][3]       = "level4";
    extDevShow.eLeakParaShow[eLeakParaAlmLevel][4]       = "level5";
    //水浸单位
    //extDevShow.eLeakParaUnit[eLeakParaNum]              = langN.show[langEnum::strMeter];  //"米";
    extDevShow.eLeakParaUnit[eLeakParaCableResist]      = "Ω";

    //spds单位 Main
    extDevShow.eSpdsMainUnit[eSpdsMainVolt_AB  ]          = "V";
    extDevShow.eSpdsMainUnit[eSpdsMainVolt_BC  ]          = "V";
    extDevShow.eSpdsMainUnit[eSpdsMainVolt_CA  ]          = "V";
    extDevShow.eSpdsMainUnit[eSpdsMainVolt_LN  ]          = "V";
    extDevShow.eSpdsMainUnit[eSpdsMainVolt_A   ]          = "V";
    extDevShow.eSpdsMainUnit[eSpdsMainVolt_B   ]          = "V";
    extDevShow.eSpdsMainUnit[eSpdsMainVolt_C   ]          = "V";
    extDevShow.eSpdsMainUnit[eSpdsMainCurr_A   ]          = "A";
    extDevShow.eSpdsMainUnit[eSpdsMainCurr_B   ]          = "A";
    extDevShow.eSpdsMainUnit[eSpdsMainCurr_C   ]          = "A";
    extDevShow.eSpdsMainUnit[eSpdsMainCurr_N   ]          = "A";
    extDevShow.eSpdsMainUnit[eSpdsMainLoad_A   ]          = "%";
    extDevShow.eSpdsMainUnit[eSpdsMainLoad_B   ]          = "%";
    extDevShow.eSpdsMainUnit[eSpdsMainLoad_C   ]          = "%";
    extDevShow.eSpdsMainUnit[eSpdsMainFreq_A   ]          = "Hz";
    extDevShow.eSpdsMainUnit[eSpdsMainFreq_B   ]          = "Hz";
    extDevShow.eSpdsMainUnit[eSpdsMainFreq_C   ]          = "Hz";
    extDevShow.eSpdsMainUnit[eSpdsMainKWhHi_A  ]          = "kW·h";
    extDevShow.eSpdsMainUnit[eSpdsMainKWhLo_A  ]          = "kW·h";
    extDevShow.eSpdsMainUnit[eSpdsMainKWhHi_B  ]          = "kW·h";
    extDevShow.eSpdsMainUnit[eSpdsMainKWhLo_B  ]          = "kW·h";
    extDevShow.eSpdsMainUnit[eSpdsMainKWhHi_C  ]          = "kW·h";
    extDevShow.eSpdsMainUnit[eSpdsMainKWhLo_C  ]          = "kW·h";
    extDevShow.eSpdsMainUnit[eSpdsMainKva_A    ]          = "kVA";
    extDevShow.eSpdsMainUnit[eSpdsMainKva_B    ]          = "kVA";
    extDevShow.eSpdsMainUnit[eSpdsMainKva_C    ]          = "kVA";
    extDevShow.eSpdsMainUnit[eSpdsMainKw_A     ]          = "kW";
    extDevShow.eSpdsMainUnit[eSpdsMainKw_B     ]          = "kW";
    extDevShow.eSpdsMainUnit[eSpdsMainKw_C     ]          = "kW";
    extDevShow.eSpdsMainUnit[eSpdsMainKVar_A   ]          = "kVar";
    extDevShow.eSpdsMainUnit[eSpdsMainKVar_B   ]          = "kVar";
    extDevShow.eSpdsMainUnit[eSpdsMainKVar_C   ]          = "kVar";
    extDevShow.eSpdsMainUnit[eSpdsMainPF_A     ]          = "";
    extDevShow.eSpdsMainUnit[eSpdsMainPF_B     ]          = "";
    extDevShow.eSpdsMainUnit[eSpdsMainPF_C     ]          = "";
    extDevShow.eSpdsMainUnit[eSpdsMainTHDU_A   ]          = "%";
    extDevShow.eSpdsMainUnit[eSpdsMainTHDU_B   ]          = "%";
    extDevShow.eSpdsMainUnit[eSpdsMainTHDU_C   ]          = "%";
    extDevShow.eSpdsMainUnit[eSpdsMainTHDI_A   ]          = "%";
    extDevShow.eSpdsMainUnit[eSpdsMainTHDI_B   ]          = "%";
    extDevShow.eSpdsMainUnit[eSpdsMainTHDI_C   ]          = "%";
    extDevShow.eSpdsMainUnit[eSpdsMainKWhHi_all]          = "kW·h";
    extDevShow.eSpdsMainUnit[eSpdsMainKWhLo_all]          = "kW·h";

    //spds单位 Branch
    extDevShow.eSpdsBranchUnit[eSpdsBranchVolt       ]    = "V";
    extDevShow.eSpdsBranchUnit[eSpdsBranchCurr       ]    = "A";
    extDevShow.eSpdsBranchUnit[eSpdsBranchLoad       ]    = "%";
    extDevShow.eSpdsBranchUnit[eSpdsBranchKWhHi      ]    = "kW·h";
    extDevShow.eSpdsBranchUnit[eSpdsBranchKWhLo      ]    = "kW·h";
    extDevShow.eSpdsBranchUnit[eSpdsBranchKva        ]    = "kVA";
    extDevShow.eSpdsBranchUnit[eSpdsBranchKw         ]    = "kW";
    extDevShow.eSpdsBranchUnit[eSpdsBranchTHDI       ]    = "%";
    extDevShow.eSpdsBranchUnit[eSpdsBranchSwSts      ]    = "";   //Switch status
    extDevShow.eSpdsBranchUnit[eSpdsBranchCurrOvUp   ]    = "";   //Current over upper limit
    extDevShow.eSpdsBranchUnit[eSpdsBranchCurrUnderLo]    = "";   //Current under lower limit

    //spds状态 branch
    for(int i=0;i<eSpdsBranchNum;i++){
        extDevShow.eAcStsShow[i][0] = "";
        extDevShow.eAcStsShow[i][1] = "";
    }
    extDevShow.eSpdsBranchShow[eSpdsBranchSwSts      ][0]    = langN.show[langEnum::strShut]; //"闭合";
    extDevShow.eSpdsBranchShow[eSpdsBranchSwSts      ][1]    = langN.show[langEnum::strCutout]; //"断开";
    extDevShow.eSpdsBranchShow[eSpdsBranchCurrOvUp   ][0]    = langN.show[langEnum::strNorm]; //"正常";
    extDevShow.eSpdsBranchShow[eSpdsBranchCurrOvUp   ][1]    = langN.show[langEnum::strAlm]; //"告警";
    extDevShow.eSpdsBranchShow[eSpdsBranchCurrUnderLo][0]    = langN.show[langEnum::strNorm]; //"正常";
    extDevShow.eSpdsBranchShow[eSpdsBranchCurrUnderLo][1]    = langN.show[langEnum::strAlm]; //"告警";

    //BMS状态
    for(int i=0;i<eBmsGroupNum;++i){
        extDevShow.eBMSGroupShow[i][0] =   langN.show[langEnum::strNorm];
        extDevShow.eBMSGroupShow[i][1] =   langN.show[langEnum::strAlm];
        extDevShow.eBMSGroupShow[i][2] =   langN.show[langEnum::strAlm];
        extDevShow.eBMSGroupShow[i][3] =   langN.show[langEnum::strAlm];
        extDevShow.eBMSGroupShow[i][4] =   langN.show[langEnum::strAlm];
    }
    extDevShow.eBMSGroupShow[eBmsGroupBattSts][0]        =   langN.show[langEnum::strBattNotWork];  //?
    extDevShow.eBMSGroupShow[eBmsGroupBattSts][1]        =   langN.show[langEnum::strBattFloat];
    extDevShow.eBMSGroupShow[eBmsGroupBattSts][2]        =   langN.show[langEnum::strBattBoost];
    extDevShow.eBMSGroupShow[eBmsGroupBattSts][3]        =   langN.show[langEnum::strBattDisChar];
    extDevShow.eBMSGroupShow[eBmsGroupBattSts][4]        =   langN.show[langEnum::strBattNotWork];  //?

    extDevShow.eBMSGroupShow[eBmsGroupBattType][0]        =   "2V";
    extDevShow.eBMSGroupShow[eBmsGroupBattType][1]        =   "6V";
    extDevShow.eBMSGroupShow[eBmsGroupBattType][2]        =   "12V";




    for(int i=0;i<eBmsCellNum;++i){
        extDevShow.eBMSCellShow[i][0] = langN.show[langEnum::strNorm];
        extDevShow.eBMSCellShow[i][0] = langN.show[langEnum::strAlm];
    }





}


